### ISSUE TITLE
Issue with Date picker icon Alignment 

### ISSUE THREAD

**Issue by vinaybtech51** [angular/material#10046]
**Actual Behavior**:
 -  By default, date picker icon is being displayed to the left side of the text field
 -  I would like to change date picker icon alignment from left to right i.e., icon should be displayed to the right side of the text field. Is there any way to make it configurable like date-picker-icon-align = "right"?
 
Please help me on this..

**Angular Versions**: *
 -  `Angular Version:1.5.5
 -  `Angular Material Version:1.1.1

**Comment by topherfangio** [comment]
You should be able to achieve this with some basic CSS updates: http://codepen.io/topherfangio/pen/RKrpEQ

In the above Codepen, I have added the following CSS to drop the input to the left of the button.

```css
.md-icon-button + .md-datepicker-input-container {
  float: left;
  margin-top:7px;
}
```
