### ISSUE TITLE
background color to some fields in form

### ISSUE THREAD

**Issue by akashjarad** [angular/material#10300]
**Actual Behavior**:
 -  `What is the issue? *` 
 angular is adding background color to some fields in form , the color is white but the transparency is 1, so in some screen it shows a light dark color in background.
 -  `What is the expected behavior?`
the background should be white .

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:1.5`
 -  `Angular Material Version:1.1.1`

**Additional Information**:
 -  `Browser Type:  chrome`
 -  `Browser Version: Version 55.0.2883.75 (64-bit)`
 -  `OS: ubuntu`
 -  `Stack Traces:`

this property is getting applied.

```css
md-content.md-default-theme, md-content {
    color: rgba(0,0,0,0.87);
    background-color: rgb(250,250,250);
}
```

when i inspect it in chrome it shows the `background-color:rgb(250,250,250)` is having its  "A" value as 1, when i manually change it to 0 every thing works fine.
