### ISSUE TITLE
sidenav,backdrop, dialog should be fixed

### ISSUE THREAD

**Issue by AlmogBaku** [angular/material#1084]
On pages with long contents the backdrop nor the sidenav not covers the whole screen while scrolling.

On my case, the solution was:
```css
.md-opaque, md-sidenav, .md-dialog-container {
  position: fixed !important;
}
```
