### ISSUE TITLE
layout: incorrect flex value for flex-gt-md='25'

### ISSUE THREAD

**Issue by UlTMATE** [angular/material#10848]
**Actual Behavior**:
 -  `What is the issue? *`
>> flex-gt-md='25' is setting flex: 1 1 100%.
 -  `What is the expected behavior?`
>> flex-gt-md='25' should set flex: 1 1 25% as it used to do in version 1.1.1

**CodePen** (or steps to reproduce the issue): *
 -  Details - If we set flex-gt-md='25' then the flex value assigned is 1 1 100% which seems incorrect. It should be flex: 1 1 25% as it used to be in angular-material version 1.1.1

**AngularJS Versions**: *
 -  `AngularJS Version:` - 1.5.8
 -  `AngularJS Material Version:` - 1.1.4

**Additional Information**:
 -  `Browser Type: *`- Google Chrome
 -  `Browser Version: *` - 59.0.3071.115 (Official Build) (64-bit)
 -  `OS: *` - macOS Sierra v10.12.6

**Comment by Leinad4Mind** [comment]
I'm using 1.1.9 and I found the same issue. And for what I checked 1.1.12 still have this problem.

Problem:

```
@media (min-width: 1280px)
.layout-column>.flex-gt-md-25 {
    max-width: 100%;
    max-height: 25%;
}
```

FIX:
The max-width should be 25% and the height 100% instead.

**Comment by Splaktar** [comment]
Please provide a CodePen demo.

As demonstrated in the [Layout Guide](https://material.angularjs.org/1.1.12/#overriding-responsive-flex-directives), it sets `max-width: 25%`:
```css
@media (min-width: 1280px)
.flex-gt-md-25, .layout-row>.flex-gt-md-25 {
    flex: 1 1 100%;
    max-width: 25%;
    max-height: 100%;
    box-sizing: border-box;
}
```
