### ISSUE TITLE
Scrollbar appears when right paginator for tabs is visible.

### ISSUE THREAD

**Issue by ahmadhsalim** [angular/material#1087]
Check the [Plunker](http://embed.plnkr.co/8kzEkzAAbqABNx6kAgyv/preview).

If you reduce the browser width which enables the paginators for the tabs. A scrollbar shows up on the bottom whenever the right paginator is visible.

I've fixed it using this code.

```css
.md-paginator{
    margin-right:0px;
}
```
