### ISSUE TITLE
gridList: demo example responsiveness broken on Safari

### ISSUE THREAD

**Issue by wangsha** [angular/material#11043]
### Bug:
Left: Safari, grid not responsive to browser resizing
Right: Chrome, behave as expected
![screenshot](https://user-images.githubusercontent.com/221029/34289966-f92968ce-e72f-11e7-93a8-12924a9058c6.png)

### What is the expected behavior?
Gridlist should be responsive on all browsers.

### What is the current behavior?
Responsiveness is broken on latest version of safari.

## Steps to reproduce the issue:
Open [material gridlist demo page](https://material.angularjs.org/latest/demo/gridList) in both safari and chrome. Resize each browser and observe the behavior.

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJS: 1.6.7
Material: 1.1.5
OS: macOS High Sierra
Browser: 11.0.2
Machine: Macbook Pro

### Is there anything else we should know? Stack Traces, Screenshots, etc.
The erroneous behaviour is caused by the line in demo css file
`transition: all 400ms ease-out 50ms;`

There is nothing listed on https://caniuse.com/#feat=css-transitions related to Safari issues with transition. (credit @Splaktar) as of date the issue is discovered.

The problem wasn't observed in previous versions of Safari. However, exact version of Safari which breaks the expected behaviour cannot be identified. The problem is solved by method of trial and error.

**Comment by Splaktar** [comment]
This appears to be caused by the following [issue](https://stackoverflow.com/a/15989719/633107) where Safari cannot handle `transition: all` properly in combination with other factors (Flexbox in this case).

After some more debugging, it looks like Safari can't handle `transition` animations of the `left` property when it uses `calc()` which `md-grid-tile` does use. It looks like the CSS Transitions spec for `left` is only a "Working Draft" at this point.

Using the following animates well in Chrome, but breaks in Safari:
```css
md-grid-tile {
  transition: width 400ms, height 400ms, background 400ms, margin-top 400ms, padding-top 400ms, color 400ms, left 400ms ease-out 50ms;
}
```
The following animates some (but looks crappy w/o `left`) in Chrome, but breaks the layout in Safari (not as bad as example 1):
```css
md-grid-tile {
  transition: width 400ms, height 400ms, background 400ms, margin-top 400ms, padding-top 400ms, color 400ms ease-out 50ms;
}
```
So it's not just `left` that is causing issues. Digging a bit deeper, it's any property that uses calc! For md-grid-tile this also includes `margin-top` and `padding-top`. 
```css
md-grid-tile {
  transition: height 400ms, background 400ms, color 400ms ease-out 50ms;
}
```
Without these the animation is basically a total waste, but layout doesn't break in Safari.
