### ISSUE TITLE
input: placeholder with label does not display placeholder in IE11

### ISSUE THREAD

**Issue by srobynk** [angular/material#11668]
#### Demo: 
https://jsbin.com/kigomilucu/1/edit?html,output

#### Detailed Reproduction Steps: 
1. Open demo in IE11 and compare with Chrome

### What is the expected behavior?
Placeholder displays when there is no value as it does in Chrome

### What is the current behavior?
Placeholder does not display

### What is the use-case or motivation for changing an existing behavior?
This is a regression in 1.1.12

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.0
- AngularJS Material: 1.1.13
- OS: Mac
- Browsers: IE11
 
### Is there anything else we should know? Stack Traces, Screenshots, etc. 
Commit that seems to have caused the issue: https://github.com/angular/material/commit/44a6946

**Comment by bersLucas** [comment]
This was working in `1.1.10` and is broken in `1.1.11` - `1.1.13`

**Comment by bersLucas** [comment]
`src/components/input/input.scss:151`
```css
md-input-container:not( .md-input-has-value ) input:not( :focus ) {
  color: transparent;
}
```
The color is applied to the input in IE11 as well here. We can add this right under it, or remove making input colors transparent.

```css
md-input-container:not( .md-input-has-value ) input:not( :focus ):-ms-input-placeholder {
  color: #757575
```

**Comment by Splaktar** [comment]
I don't have time to test right now, but does the following resolve this on IE11?
```scss
  &:not(.md-input-has-value):not(.md-input-has-placeholder) input:not(:focus) {
    color: transparent;
  }
```
