### ISSUE TITLE
mdBottomSheet not positioned on the bottom the right way.

### ISSUE THREAD

**Issue by tforbus** [angular/material#1211]
I've created a bottomSheet, but its position is not correct.
Regardless of the content in the sheet, it goes lower than the bottom of the page, resulting in a scrollbar appearing. 

This is the CSS for the sheet.
```
md-bottom-sheet {
position: absolute;
left: 0;
right: 0;
bottom: 0;
padding: 8px 16px 88px;
z-index: 70;
border-top: 1px solid;
-webkit-transform: translate3d(0,80px,0);
transform: translate3d(0,80px,0);
transition: all .4s cubic-bezier(0.25,.8,.25,1);
transition-property: -webkit-transform;
transition-property: transform;
```

Here is the markup for the sheet:

```
<md-bottom-sheet class='md-grid'>
</md-bottom-sheet>
```

I'm using 0.6.1

My workaround so far is just adding a lot of padding to the md-bottom-sheet to get the contents to appear.

**Comment by EladBezalel** [comment]
Can you please provide plunker or codepen so we can review the problem live?

**Comment by PaulMougel** [comment]
Here's a basic Plunker that you can fork, if that helps: http://plnkr.co/edit/G0CCmRfi9CHxCPkwkiND (don't forget to change the version of angular-material in the included files).

**Comment by mckenzielong** [comment]
>Regardless of the content in the sheet, it goes lower than the bottom of the page, resulting in a scrollbar appearing.

Here is a plunker demonstrating this: http://embed.plnkr.co/PulmZ2gQSFN7THSLZnzS/preview

Looks like this is due to the css defaults.  Padding on the bottom of the sheet is set to 80px, yet the box is positioned absolutely at the bottom.  This results in the 80px overhanging the bottom of the page.  

From bottomSheet.scss:
```scss
md-bottom-sheet {
   ...
   $bottom-sheet-hidden-bottom-padding: 80px !default;
   ...
   transform: translate3d(0, $bottom-sheet-hidden-bottom-padding, 0);
   ...
}
...
&.ng-enter-active {
   ...
   transform: translate3d(0, $bottom-sheet-hidden-bottom-padding, 0) !important;
}
```

Should $bottom-sheet-hidden-bottom-padding default to 0 instead of 80?
