### ISSUE TITLE
select: changes scroll position when closed with bootstrap 5

### ISSUE THREAD

**Issue by mahogato** [angular/material#12134]
### Actual behavior

It's the same bug as #10588 but i found it again when i installed bootstrap 5.

I found out it's because this css code, on bootstrap:

```css
@media (prefers-reduced-motion: no-preference) {
  :root {
    scroll-behavior: smooth;
  }
}
```

More concretely:
https://github.com/twbs/bootstrap/blob/58ffe2334a94a061afab87c9fd1266445016bca5/scss/_reboot.scss#L28

### Possible solution

I added this code in my styles.css but i don't know if this affects elsewhere:

```css
@media (prefers-reduced-motion: no-preference) {
  :root {
    scroll-behavior: unset;
  }
}
```

### Codepen

[Example with the "solution"](https://stackblitz.com/edit/angularjs-material-blank-ckmdjt?file=style.css)

### Versions

- AngularJS: 1.8.2
- AngularJS Material: 1.2.3
- Bootstrap: 5.1.3
