### ISSUE TITLE
Input type date/time labels and "placeholders" conflict

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1409]
![screen shot 2015-02-05 at 6 58 13 pm](https://cloud.githubusercontent.com/assets/3695164/6071884/fc491eea-ad68-11e4-94ff-7275f566afd0.png)
The input "placeholders" are created by the browser (Chrome in this particular picture), not me.

**Comment by gustavohenke** [comment]
Possible fix:
https://groups.google.com/d/msg/ngmaterial/B6Z9QBDMw-c/4uhS-j7V1c0J

**Comment by marcysutton** [comment]
That does seem like a decent solution, since we'd want to keep the native keyboards for mobile but change the styling. From @gustavohenke's awesome suggestion on the forum:

```css
md-input-container:not( .md-input-has-value ) input:not( :focus )::-webkit-datetime-edit-ampm-field,
md-input-container:not( .md-input-has-value ) input:not( :focus )::-webkit-datetime-edit-day-field,
md-input-container:not( .md-input-has-value ) input:not( :focus )::-webkit-datetime-edit-hour-field,
md-input-container:not( .md-input-has-value ) input:not( :focus )::-webkit-datetime-edit-millisecond-field,
md-input-container:not( .md-input-has-value ) input:not( :focus )::-webkit-datetime-edit-minute-field,
md-input-container:not( .md-input-has-value ) input:not( :focus )::-webkit-datetime-edit-month-field,
md-input-container:not( .md-input-has-value ) input:not( :focus )::-webkit-datetime-edit-second-field,
md-input-container:not( .md-input-has-value ) input:not( :focus )::-webkit-datetime-edit-week-field,
md-input-container:not( .md-input-has-value ) input:not( :focus )::-webkit-datetime-edit-year-field,
md-input-container:not( .md-input-has-value ) input:not( :focus )::-webkit-datetime-edit-text {
  color: transparent;
}
```

My question (without stopping what I'm doing to go try it out): do the selectors have to be that verbose? Should the color be transparent only when it's not focused or has a value?

**Comment by gustavohenke** [comment]
Hmmm... well, I don't know what I was thinking when writing that huge selector. Looks pretty obvious now! Probably, some question in StackOverflow bit me.

This one will work:

```css
md-input-container:not( .md-input-has-value ) input:not( :focus ) {
     color: transparent;
}
```

Demo: http://plnkr.co/edit/JAWVTQQKzgXtLH9N12tQ?p=preview
