### ISSUE TITLE
md-tooltip text is hard to see

### ISSUE THREAD

**Issue by breeswish** [angular/material#1480]
gray text in black background
I found that in CSS, text color is nearly white. why it is rendered as gray?

**Comment by epelc** [comment]
+1 it use to be white I think `0.8.0-rc1` changed this. But It is incredibly hard to see now.

**Comment by breeswish** [comment]
a quick fix:

```css
md-tooltip .md-content {
    position: relative;
    opacity: 1;
}
```

However there are still bugs. if you move in and instantly move out, you would see remarkble white text. This is because the circle wave cannot crop texts. It is just a background. This is a complicated problem I think, and I'm afraid the only simple way to solve it is to remove the wave effect.
