### ISSUE TITLE
mdSelect: Persistent disabled scroll bar in Chrome

### ISSUE THREAD

**Issue by ngraef** [angular/material#1650]
As mentioned in my comment on #1628, commit c5c5f8603e631665d93c018bc6f94df2c4125eab introduced a persistent disabled scroll bar to all md-selects in Chrome.
**Non-scrolling select**
![image](https://cloud.githubusercontent.com/assets/1031317/6362239/8f5ff438-bc50-11e4-82c4-8a182d4f7e16.png)
**Scrolling select**
![image](https://cloud.githubusercontent.com/assets/1031317/6362228/6f7c5b52-bc50-11e4-8a82-211d148fad5e.png)

**Comment by ngraef** [comment]
It looks like this should fix it for both browsers.
```css
md-select-menu {
    overflow-y: auto;
    overflow-x: hidden;
}
```
