### ISSUE TITLE
Unable to Set Size for md-icon using Iconset and CSS Styling

### ISSUE THREAD

**Issue by nkoterba** [angular/material#1678]
I'm trying to use iconsets as described on the angular material demo for [md-icon](https://material.angularjs.org/#/demo/material.components.icon).

I grabbed the demo `core-icons.svg` file.

I included the following code in my angular app:
```javascript
		.config(['$mdIconProvider', function($mdIconProvider) {
			$mdIconProvider
				.iconSet('core', '../styles/images/icons/material-design/core-icons.svg', 24)
		}])
```

My html:
```html
	<md-button ng-click="vm.showNewDialog($event)">
	         <md-icon md-svg-icon="core:alarm"
		          style="color: yellow; height: 10px; width: 10px"></md-icon>
		<span>New</span>
	</md-button>
```

However, my image does not resize, the md-icon element just gets resized, clipping the md-icon.
![image](https://cloud.githubusercontent.com/assets/2508944/6386775/596afe92-bd4d-11e4-91a3-7d15b756e3e1.png)

Using the chrome inspector, we can see this:
![image](https://cloud.githubusercontent.com/assets/2508944/6386777/608992e2-bd4d-11e4-8ac6-f98656dc2bb6.png)

Oddly, loading icons from svg URLs **does work** if we apply css styles to them:
```html
      <md-icon md-svg-src="img/icons/cake.svg"            class="s24" alt="Cake"    ></md-icon>
      <md-icon md-svg-src="{{ getAndroid() }}"            class="s36" alt="Android "></md-icon>
      <md-icon md-svg-src="img/icons/addShoppingCart.svg" class="s48" alt="Cart"    ></md-icon>
```

where *s24*, *s36*, *s48* are CSS classes with height and width set:
```css
.icondemoLoadSvgIconsFromUrl .s24 {
  width: 24px;
  height: 24px;
  color: #f00; }
.icondemoLoadSvgIconsFromUrl .s36 {
  width: 36px;
  height: 36px;
  color: #0f0; }
.icondemoLoadSvgIconsFromUrl .s48 {
  width: 48px;
  height: 48px;
  color: #00f; }
```

Has anybody else experienced this or found a solution?
