### ISSUE TITLE
mdSidenav: 100% on small screens

### ISSUE THREAD

**Issue by vitoller** [angular/material#1729]
when using mdSidenav as Master/Detail controller on a small screen, it might not use the full screenwidth for the display.
It would be great to have a way to make mdSidenav slide open 100% on smaller screens.

**Comment by marcysutton** [comment]
How would you get out of it without swiping?

**Comment by rrharvey** [comment]
The Material design [whiteframes template](http://www.google.com/design/spec/resources/layout-templates.html#layout-templates-tablet) has a layout that looks similar to this idea in the fourth set of layouts. There is a close X in the top corner. It doesn't really match the description of the navigation drawer in the spec though.
I would still love to have this as an option.

![2015-03-03_0802](https://cloud.githubusercontent.com/assets/2002141/6465120/2cee30cc-c17c-11e4-8558-ca0f0770dd3f.png)

**Comment by ThomasBurleson** [comment]
@vitoller - Use CSS to force the SideNav full-width. On the [Angular Material](http://material.angularjs.org) site you use the following css to force full-width:

```css
.site-sidenav, .site-sidenav.md-locked-open-add-active, .site-sidenav.md-locked-open {
width: 100%;
min-width: 254px;
max-width: 100%;
}
```

Closed. @See #1765.
