### ISSUE TITLE
Improve styles for @media print

### ISSUE THREAD

**Issue by epelc** [angular/material#1747]
The current styles for `@media print` need a bit of work. `md-sidenav` takes up half the screen and `md-content` only shows the visible area instead of the whole page. `md-fab` buttons are also shown which seems like it isn't necessary. 

Perhaps a designer can comment but a decent solution(depending on whats in your sidenav) is to just hide sidenavs entirely for the `print` media query. Also perhaps `show/hide-*` classes for all the different media queries would be a good idea.

**Comment by DavidSouther** [comment]
I would be very pleased if this "just worked". I have a print report user story coming up, and if material styles just "handled" them that would be fantastic. On the other hand, I don't know of any place in the Material spec that mentions print styles.

**Comment by epelc** [comment]
@DavidSouther They mostly do work. But as I said the sidenav needs some work and I had to add a few styles to fix `md-content` only showing what you currently see.

Here's what I came up with
```
@media print {
    md-sidenav, .md-fab {
        display: none !important;
    }

    md-content {
        overflow: visible;
    }

    .print-full {
        page-break-inside: avoid;
    }
}
```

**Comment by DavidSouther** [comment]
@epelc thanks for that! I'll try it out later this week, and use those if I need them.

**Comment by no-more** [comment]
Hi,

Would it be possible to flatten tabs when printing? It would be great if we could print all tab contents at the same time while using the tab label as some kind of section title.

I'm not sure this can be done only with css, but I might be wrong.

Thanks a lot.

**Comment by ThomasBurleson** [comment]
@epelc - How about submitting a PR for improved printing styles.

**Comment by epelc** [comment]
@ThomasBurleson I'm up for a PR. It might have to wait until next week as I'm traveling/pretty busy this week though.

But would you be ok with me adding `show/hide-print` attributes? I think this would be helpful to easily let users decide if they want their elements to hidden for printing. Specifically I think this would be best for the sidebar as I think it's more a per app choice. For example showing the sidebar while printing works well for the docs but in my app it doesn't do too well.

Besides that I just think `md-content` needs `overflow: visible;` and possibly something else to make long dialogs work now that I think of it.

**Comment by ThomasBurleson** [comment]
@epelc - let's explore your ideas via a PR.

**Comment by holdfenytolvaj** [comment]
Checkboxes also need extra print rules, as they are invisible (with background-color removed) when they are checked...
A minimum rule would be:
```css
@media print {
    md-checkbox.md-checked .md-icon:after {
        border-color: rgba(0,0,0,0.54)!important;
    }
}
```

but might be better with borders, although in this form, it doesn't add back the border for some reason... 
```css
@media print {
    md-checkbox.md-checked .md-icon:after {
        border-color: rgba(0,0,0,0.54)!important;
        left: 4px!important;
        top: 0px!important;
    }
    md-checkbox.md-checked .md-icon {
        border-radius: 2px!important;
        border: rgba(0,0,0,0.54) solid 2px !important;
    }
}
```

**Comment by nicgirault** [comment]
I've got this issue trying to print a form with radio buttons. The difference between checked radio button and unchecked radio button is very tight

**Comment by SimonBiggs** [comment]
If others find this by google I was able to fix this using:

```css
@media print {
  body {
    -webkit-print-color-adjust: exact;
    color-adjust: exact;
  }
}
```
