### ISSUE TITLE
md-select not properly aligned with other inputs

### ISSUE THREAD

**Issue by jgoux** [angular/material#1755]
As you can see here : http://plnkr.co/edit/wX6cKJkYHxRIJDXZB2ml?p=preview `md-select` isn't exactly aligned with the other inputs.
As a quick fix in the CSS : 
```css
md-select {
    margin-top: 1.25em;
}
```

EDIT : In fact it seems that it's perfectly aligned using Roboto fonts. Should it be "font agnostic" ?
