### ISSUE TITLE
Angular Content Security Policy (ng-csp) completely breaks md-tabs

### ISSUE THREAD

**Issue by Gambloide** [angular/material#1993]
In version 0.8.3 [enabling CSP support](https://docs.angularjs.org/api/ng/directive/ngCsp) always displays all the `md-tab` objects at once, animations *(almost completely)* break and the view always instantly returns to the initial state after the animation ends.

[Here is a plunk of what it looks like.](http://plnkr.co/edit/Iv6QroDEUmY61wC6HYMz)

*I forked that one from [hodepy](https://github.com/hodeyp)'s plunk in issue #1788*

Removing the `ng-csp` attribute from the html presents the expected behavior. However, this directive is mandatory for Chrome Apps/Extensions and Universal Windows Apps, which is what I am aiming to use this for. Since I haven't used Angular Material before I don't know if this is an issue introduced by the recent rewrite of `md-tabs` commit 865d856ff3d354853ab7565102b230796549d0f3 or if it is related to something else.

Seeing as it breaks behavior normally accomplished via CSS I assumed it was because there was inline CSS used in the directives, which breaks if CSP support is enabled, however, I was unable to find anything in the generated markup with CSP disabled.

Maybe someone more familiar with the project has an idea or even some more branches lying around on which to test this?

**Comment by Gambloide** [comment]
#### This is not a Problem with Angular Material

After comparing the generated markup with and without the `ng-cdp` attribute I found that the CSP enabled version was missing an injected `<style type="text/css">` block in the `<header>`.

##### The block in question
```html
<style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\:form{display:block;}</style>
```

#### The Solution
After searching for these rules in all modules I found this under `node_modules/angular/angular-csp.css`
```css
/* Include this file in your html if you are using the CSP mode. */

@charset "UTF-8";

[ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak],
.ng-cloak, .x-ng-cloak,
.ng-hide:not(.ng-hide-animate) {
  display: none !important;
}

ng\:form {
  display: block;
}
```

So after all this is an issue with AngularJS itself. It seems there was a breaking change introduced since the last time I worked on an AngularJS project that I was not aware of. I am sorry for the noise and just hope this will help someone else in the future maybe coming across this issue as well.
