### ISSUE TITLE
Support for md-icon coloring using webfont in md-input-container

### ISSUE THREAD

**Issue by jgoux** [angular/material#2024]
Hi,
the current implementation of inputs with icon as label supports only SVG icons.
On focus, the icon is colored, on error as well.
Could you add a `color` css attribute along with the `fill` to allow webfonts icon to be colored too ?

**Comment by ThomasBurleson** [comment]
Color support using styling:  https://material.angularjs.org/#/demo/material.components.icon
Focus Icon coloring (see last demo Icon): https://material.angularjs.org/#/demo/material.components.input 

You can easily customize your own md-input-container icon colors:

Normal:
```css
md-input-container > md-icon {
	color : 'black';
}
``

Focused
````css
md-input-container:not(.md-input-invalid).md-input-focused md-icon {
	color : 'red';
}
```
