### ISSUE TITLE
$mdToast is not full width

### ISSUE THREAD

**Issue by marlonmleite** [angular/material#2046]
I'm set position in my $mdToast:
```css
position('left right')
```

This is not full width.

Example:
![toast-no-full](https://cloud.githubusercontent.com/assets/8551142/6868633/effbb6c8-d46b-11e4-8430-ebd90a2b5fa0.jpg)

To solve this, I had to put the max-width: 100%; in css to override the max-width: 879px; the $mdToast default.
```css
md-toast {
 max-width: 100%;
}
```
Result:
![toast-full](https://cloud.githubusercontent.com/assets/8551142/6868645/094b5af2-d46c-11e4-9af8-dd9d3ce1a8f5.jpg)

This is correct behavior? Limit width $mdToast to 879px?

----

Another nice solution without informing max-width: 100%, would be to use the code below:
```css
md-toast {
  margin-left: auto;
  margin-right: auto;
}
```
Result:
![toast-center](https://cloud.githubusercontent.com/assets/8551142/6868677/57bbd428-d46c-11e4-8c17-35f4c5cf1ddc.jpg)
