### ISSUE TITLE
mdTabs content gets cut short.

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [angular/material#2059]
On the tabs demo, when viewing the source, even after scrolling all of the way down in the tabs content, part of the content gets cut off.

![image](https://cloud.githubusercontent.com/assets/7330103/6876929/b81803ec-d4a2-11e4-81f2-2a59f479c39a.png)

This also occurs on my page, which may be more visible. 
![image](https://cloud.githubusercontent.com/assets/7330103/6876960/ee123c24-d4a2-11e4-9184-967c113d1b10.png)

**Comment by WhiteAbeLincoln** [comment]
It looks like `$tabs-header-height` is not being resolved in this code from commit 0e1820c, since the max height of the tab content ends up being 200px

```scss
 border-radius: 2px;
   overflow: hidden;
   position: relative;
-  &:not('.md-no-tab-content') {
+  &:not(.md-no-tab-content) {
     min-height: 200 + $tabs-header-height;
   }
   &[md-align-tabs="bottom"] {
```

![image](https://cloud.githubusercontent.com/assets/7330103/6877092/21d86e60-d4a4-11e4-8441-a09df305172a.png)
