### ISSUE TITLE
md-align-tabs doesn't work in firefox or chrome

### ISSUE THREAD

**Issue by grantopher** [angular/material#2119]
I have tried in many different environment setups but I cannot get the md-align-tabs to position the tabs below the tabbed content. Is this a bug inside of Material or am I simple using this wrong? 
http://plnkr.co/edit/7IUUauGoo7Wl585JpveL?p=preview

**Comment by IVLMediaInc** [comment]
Also experiencing this issue.

**Comment by viztastic** [comment]
Can confirm same issue

**Comment by ThomasBurleson** [comment]
This may be a feature that has not yet been migrated to the 0.9 version of Tabs.

**Comment by viztastic** [comment]
@ThomasBurleson Is there a CSS 'hack' for us to get by until the next release of ngMaterial?

**Comment by ThomasBurleson** [comment]
@viztastic - Here is a **temporary** hack that should work:

```css
md-tabs-content-wrapper {
  display: block;
  min-height: 200px;
  position: absolute;
  top: 0;
  bottom: 48px;
}

md-tabs.md-default-theme md-tabs-wrapper {
  display:block;
  position: absolute;
  height: 48px;
  min-height:48px;
  max-height:48px;
  bottom: 0px;
}
```
