### ISSUE TITLE
Feature request: layout-gap

### ISSUE THREAD

**Issue by ericwfisher** [angular/material#2360]
I add the following css to my material projects so often that I thought it might be of value to others. CSS is pasted below. The intent is to insert a gap between the immediate flex children of an element defining both the layout and layout-gap attributes. The result is a column or row of items that have an 8px gap between each item but no gap/margin applied to the final element nor to a single item.
```css
[layout=column][layout-gap] > [flex]:not(:last-child) {
  margin-bottom: 8px;
}

[layout=row][layout-gap] > [flex]:not(:last-child) {
  margin-right: 8px;
}
```
