### ISSUE TITLE
md-select is causing elements to re-animate

### ISSUE THREAD

**Issue by prestonvanloon** [angular/material#2369]
When clicking to select from md-select, object animations are run again since elements are inserted into the DOM again.

Example: http://plnkr.co/edit/o6dugqwtpR4sXsyMyQWb?p=preview

**Comment by rschmukler** [comment]
I added a `.md-overflow-wrapper-shown` class that will allow you to do a rule like the following:

```css
.md-overflow-wrapper-shown .animated { animation-name: none !important; }
```

This will break animations after the select has been shown, so really a more viable solution is to write a directive. Something [like this](http://jsfiddle.net/rschmukler/nzv53w5L/)

**Comment by prestonvanloon** [comment]
Thank you! 

In my case, the CSS class works well.

```css
.md-overflow-wrapper-shown .animated { 
  -o-animation-name:      none !important;
  -moz-animation-name:    none !important;
  -webkit-animation-name: none !important;
  animation-name:         none !important; 
}
```
