### ISSUE TITLE
md-progress-linear doesn't show progress bar in content area

### ISSUE THREAD

**Issue by brlam** [angular/material#2540]
md-progress-linear doesn't show the progress bar in the content area but shows it right below it instead. You can see this in the demo: https://material.angularjs.org/#/demo/material.components.progressLinear. The bar is drawn in the margin area of the md-progress-linear element and the content area is empty. This is because there is a top declaration in the bar container that is equal to the height declarations of both the container and the larger element.

I am creating a UI element that has a progress bar flush against the top of another element and noticed that the bar wasn't showing because of this.

Example: http://codepen.io/anon/pen/NqWeda
You would expect the progress bar to be touching the top lime outline. It is instead in the top of the black box. If the black box were drawn on top of the progress bar, the progress bar would not be seen at all.

From material/src/components/progressLinear/progressLinear.scss
```SCSS
$progress-linear-bar-height:5px !default;

md-progress-linear {
  display: block;
  width: 100%;
  height: $progress-linear-bar-height;

  .md-container {
    overflow: hidden;
    position: relative;
    height: $progress-linear-bar-height;
    top: $progress-linear-bar-height;  /* <--- Why is this here? */
    transform: translate(0, 5px) scale(1, 0);
    transition: all .3s linear;
  }
}
```
