### ISSUE TITLE
flex-grow vs flex

### ISSUE THREAD

**Issue by tkrotoff** [angular/material#2632]
Edit: my original mistake when I wrote this issue was to believe that `flex-shrink` in the context of `flex-wrap: wrap` was responsible for the widgets to shrink below their "natural" size => it is in fact "controlled" (more of a side effect?) by `flex-basis`.

<br>

tl;dr attribute `flex-grow` is most probably what users want instead of `flex`.

ngMaterial defines the `flex` attribute:
```CSS
[flex] {
  flex: 1; /* Shorthand for flex-grow: 1; flex-shrink: 1 */
}
```
You "advertise" its use everywhere like it is the most common pattern. The item grows when space is available (good) and shrinks up to nothing if there is no space (not good). I believe this is not the most common use case.
A better approach is to not shrink below the "natural" item/widget size if space is lacking. (If I remember well, this is what GTK+, Qt and Java Swing do).

Demo: http://plnkr.co/edit/vjud32?p=preview

![](http://s9.postimg.org/mrlve12u7/flex.png)

I propose to define `flex-grow` attribute and use it instead of `flex`:
```CSS
[flex-grow] {
  box-sizing: border-box;
  flex-grow: 1;
}
```

I don't think it is worth to define `flex-shrink` attribute: I do not believe it is a common pattern.
