### ISSUE TITLE
Ionic Conflict: Html type attribute

### ISSUE THREAD

**Issue by atentis** [angular/material#2758]
When you use Ionic + Material with the html type attribute you will have css issues. As you can see in the plunk the bottom line is missing from the input when using the type=password

http://plnkr.co/edit/n0qfNhYbsCHrCIrLx3Bv?p=preview

**Comment by marcysutton** [comment]
It's from this line in ionic.css:
```css
textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"] {
  border: 0; }
```
Those types are more specific than `md-input-container .md-input`, so the border is being turned off. We'll have to experiment with the right specificity, since it looks like the ionic stylesheet is already being loaded first.
