### ISSUE TITLE
Md-Tab-Item Should Disable Text Selection?

### ISSUE THREAD

**Issue by j-meyer** [angular/material#2940]
I'm not sure if this is a bug or not, but I feel like md-tab-item should by default have user-select: none; as part of its style, otherwise when a user clicks on a tab, it's possible for the label in the tab to be selected and it looks weird.

**Comment by cnpal** [comment]
you could try `user-select: none` in your css, solves it for me. 

e.g. for the whole page (more app-alike)

    *, *:after, *:before {
        -webkit-user-select: none;
        -ms-user-select: none;
        -moz-user-select: -moz-none;
        user-select: none;
    }

**Comment by OlsonDev** [comment]
@cnpal Not sure if you meant that snippet to be sent through a preprocessor, but in a plain-old stylesheet it needs to be:

```css
:not(input):not(textarea),
:not(input):not(textarea):after,
:not(input):not(textarea):before {
    -webkit-user-select: none;
    -ms-user-select: none;
    -moz-user-select: -moz-none;
    user-select: none;
}
```

See https://developer.mozilla.org/en-US/docs/Web/CSS/%3Anot#Browser_compatibility and http://dev.w3.org/csswg/selectors-3/#simple-selectors-dfn
