### ISSUE TITLE
.md-button.md-default-theme.md-accent has a red-based color.

### ISSUE THREAD

**Issue by mbarakaja** [angular/material#3018]
Hello.

I started today testing some components from the master branch and the `md-button` directive with the class `md-accent` has the next rule:

```css
button.md-default-theme.md-accent {
  color: rgb(255,64,129);
}
```

This render a red-based color, that is pretty much the same as `md-warn`. But in the documentation demos the color is gree-based. As it expected.

Is this correct?
