### ISSUE TITLE
Material Icons on md-icon directive

### ISSUE THREAD

**Issue by edaquinta** [angular/material#3036]
I have a question, sorry for my english btw, I found (http://google.github.io/material-design-icons/), a great icon set but didn't find a individual css class implementation for each icon, just Ligatures, so if I want to use the < md-icon > directive with the md-font-icon="menu" attribute I can't. Maybe there is a better way, I just didn't find it and create my own approach:

CSS
.menu:after { content: "\E5D2" }

HTML
< md-icon md-font-icon="menu" >< /md-icon >

so I define the icons I'll be using and that's it. make sense? If there is a better way let me know, and if no exist and your OK with mine, I can send you my CSS implementation, is that easy as include the material-icons web font from google and the new css with the individual definitions.

**Comment by ThomasBurleson** [comment]
Here are the general steps we used in our [Font Icon Demo]():

1.  Load the icon fonts desired
1.  Configure CSS with names to specify a content unicode
1.  Use font icon name in md-font-icon="<css name>"

### Loading the fonts

```html
<style>
    @font-face {
      font-family:"icomoon";
      src:url("https://cdn.rawgit.com/angular/material/master/docs/app/fonts/icomoon.eot");
      font-weight:normal;
      font-style:normal;
    }
    @font-face {
      font-family: 'icomoon';
      src:url('https://rawgit.com/angular/material/master/docs/app/fonts/icomoon.eot?-cmq1um');
      src:url('https://cdn.rawgit.com/angular/material/master/docs/app/fonts/icomoon.eot?#iefix-cmq1um') format('embedded-opentype'),
      url('https://cdn.rawgit.com/angular/material/master/docs/app/fonts/icomoon.woff?-cmq1um') format('woff'),
      url('https://cdn.rawgit.com/angular/material/master/docs/app/fonts/icomoon.ttf?-cmq1um') format('truetype'),
      url('https://cdn.rawgit.com/angular/material/master/docs/app/fonts/icomoon.svg?-cmq1um#icomoon') format('svg');
      font-weight: normal;
      font-style: normal;
    }
  </style>
```

or using 

```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
```

### Specifying the CSS

Since our font-icon css names have an `icon-` prefix, we can easily specify the `font-family` in the css.

```css
    [class^="icon-"]:before,
    [class*=" icon-"]:before {
      /** associate font-family with font icons names */
      font-family:"icomoon";
      display:inline-block;
      vertical-align:middle;
      line-height:1;
      font-weight:normal;
      font-style:normal;
      speak:none;
      text-decoration:inherit;
      text-transform:none;
      text-rendering:optimizeLegibility;
      -webkit-font-smoothing:antialiased;
      -moz-osx-font-smoothing:grayscale;
    }

    .icon-home:before {
        content: "\e900";
    }
```

And our names are `.icon-home`, etc.

### Using `<md-icon>`

Simply set the `md-font-icon` attribute and any `color: #xxx` css to specify the fill color:

```html
<md-icon md-font-icon="icon-home" />
```

**Comment by edaquinta** [comment]
This is basically the same thing I'm doing, instead using icon-* I set the font family to all the md-icon:

md-icon > .md-font {
    font-family: 'Material Icons';
    font-weight: normal;
    font-style: normal;
    font-size: 24px;  /* Preferred icon size */
    display: inline-block;
    width: 1em;
    height: 1em;
    line-height: 1;
    text-transform: none;

    /* Support for all WebKit browsers. */
    -webkit-font-smoothing: antialiased;
    /* Support for Safari and Chrome. */
    text-rendering: optimizeLegibility;

    /* Support for Firefox. */
    -moz-osx-font-smoothing: grayscale;

    /* Support for IE. */
    font-feature-settings: 'liga';
}

and then create the names with content unicode. So there isn't a CSS created with all the Material Icons individual icons right?

**Comment by dparish** [comment]
I found this very confusing as well. Funny that the issue was JUST created. Angular material's md-icon makes it appear as if you get a large icon set, but in reality it appears you only get the 4 or 5 in the demo.  Some sort of hook to the http://google.github.io/material-design-icons/ icons and how to hook them up would certainly be appreciated.  

It seems silly to have to create css entries for each icon when all I need to use the icons in the material icon bundle is:
```
<i class="material-icons">face</i>
```
I should be able to just do:
```
<md-icon md-font-icon="face"></md-icon>
```
without having to do a css entry for "face"

**Comment by edaquinta** [comment]
Yes, actually that's what I'm doing, making the hook for my personal use jejejeje. Just creating the CSS with the definition of every single icon in the css in order to be able to use it in the md-icon way. So in the future I just use < md-icon md-font-icon="face" >< /md-icon > cause I already define all ligatures as class names. make sense? Sorry for my english

**Comment by dparish** [comment]
I'm surprised this doesn't work:

```
    <md-button class="md-fab" aria-label="FAB">
        <i class="material-icons">face</i>
    </md-button>
```
It won't show the icon even when it works by itself:

```
        <i class="material-icons">face</i>
```

**Comment by edaquinta** [comment]
By the way, if you wanna use it in the easy way, just use my css (https://github.com/edaquinta/angular-material-icons).
Regards

**Comment by vanntian** [comment]
@edaquinta https://www.google.com/design/icons/#ic_check_box google already provided this.😄

**Comment by edaquinta** [comment]
No dude, this is where I took the unicode values but they don't provide a css with the class name, something required in md-icon directive, not the ligature. make sense?

**Comment by ThomasBurleson** [comment]
Here are the general steps we used in our [Font Icon Demo]():

1.  Load the icon fonts desired
1.  Configure CSS with names to specify a content unicode
1.  Use your custom css name in md-font-icon="<css name>"

### Loading the fonts

```html
<style>
    @font-face {
      font-family:"icomoon";
      src:url("https://cdn.rawgit.com/angular/material/master/docs/app/fonts/icomoon.eot");
      font-weight:normal;
      font-style:normal;
    }
    @font-face {
      font-family: 'icomoon';
      src:url('https://rawgit.com/angular/material/master/docs/app/fonts/icomoon.eot?-cmq1um');
      src:url('https://cdn.rawgit.com/angular/material/master/docs/app/fonts/icomoon.eot?#iefix-cmq1um') format('embedded-opentype'),
      url('https://cdn.rawgit.com/angular/material/master/docs/app/fonts/icomoon.woff?-cmq1um') format('woff'),
      url('https://cdn.rawgit.com/angular/material/master/docs/app/fonts/icomoon.ttf?-cmq1um') format('truetype'),
      url('https://cdn.rawgit.com/angular/material/master/docs/app/fonts/icomoon.svg?-cmq1um#icomoon') format('svg');
      font-weight: normal;
      font-style: normal;
    }
  </style>
```

or using 

```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
```

### Specifying the CSS

Since our font-icon css names have an `icon-` prefix, we can easily specify the `font-family` in the css.

```css
    [class^="icon-"]:before,
    [class*=" icon-"]:before {
      /** associate font-family with font icons names */
      font-family:"icomoon";
      display:inline-block;
      vertical-align:middle;
      line-height:1;
      font-weight:normal;
      font-style:normal;
      speak:none;
      text-decoration:inherit;
      text-transform:none;
      text-rendering:optimizeLegibility;
      -webkit-font-smoothing:antialiased;
      -moz-osx-font-smoothing:grayscale;
    }

    .icon-home:before {
        content: "\e900";
    }
```

And our css names - unique for each desired icon - are easy: `.icon-home`, etc.

### Using `<md-icon>`

Simply set the `md-font-icon` attribute and any `color: #xxx` css to specify the fill color:

```html
<md-icon md-font-icon="icon-home" />
```

----

We are currently enhancing md-icon to support font-icons libraries with ligatures:

```html
<md-icon md-font-library="material-icons">face</md-icon>
<md-icon md-font-library="material-icons">&#xE87C;</md-icon>
<md-icon md-font-library="material-icons" class="md-light md-48">face</md-icon>
``` 


The tutoria [Material Design Icons](http://google.github.io/material-design-icons/#icon-font-for-the-web)  has details describing the above approach.
