### ISSUE TITLE
Menu with icon not aligned with firefox

### ISSUE THREAD

**Issue by Alexandre-io** [angular/material#3292]
Hello,

Maybe duplicate but menu with icon is not aligned with firefox.

![capture](https://cloud.githubusercontent.com/assets/8135542/8191428/45c069e6-1468-11e5-99e4-fb4c78fe1d60.PNG)

related to "display:flex"

**Comment by arcxyz** [comment]
Same here.
Firefox 38.0.5 and 40.0a2

**Comment by ThomasBurleson** [comment]
Seems to be related to the override `display:flex` in the **md-menu-item**.
This change fixes it:

```css
md-menu-item > .md-button {
    display: inline-table;
}
```
