### ISSUE TITLE
Change md-tabs 'header' height/padding

### ISSUE THREAD

**Issue by Seiifer** [angular/material#3421]
How can we change the height and padding (mainly padding-top) of the label container ? (the `md-tabs` header used to navigate between tabs)

```css
.md-padding {
     padding: 0px; !important;
 }
```

Doesn't seem to overwrite the 16px padding in angular-material.min.css

Regards.

**Comment by dmarg** [comment]
@Seiifer This worked for me to change the ink-bar color.
```css
md-tabs md-ink-bar {
  background-color: black;
}
```
