### ISSUE TITLE
md-menu Firefox 40, Icon and text are not aligned in the dropdown.

### ISSUE THREAD

**Issue by m0g** [angular/material#3439]
In the latest version of angular-material (v0.10), the icon are not aligned on Firefox.

Here is an example:
![screenshot from 2015-06-24 14 51 13](https://cloud.githubusercontent.com/assets/1441121/8329342/57342e6e-1a81-11e5-8bee-1430d0501570.png)

**Comment by ThomasBurleson** [comment]
Need to use:

```css
md-menu-item > .md-button {
display: inline-block;
}
```
