### ISSUE TITLE
Overly broad box-sizing in grid-list and toolbar.

### ISSUE THREAD

**Issue by jelbourn** [angular/material#3516]
Both md-toolbar and md-gridlist have a rule like
```css
md-grid-list * {
  box-sizing: border-box;
}
```

This is a problem because these components are containers for arbitrary content. As such, any other components or existing content can be messed up by this overly broad style. The rules should only target elements that ng-material itself creates.
