### ISSUE TITLE
md-select md-options :hover and :focus styles aren't accessible

### ISSUE THREAD

**Issue by OlsonDev** [angular/material#3526]
From what I can tell, the spec does not explicitly require `:hover` styles on select dropdown items or on menu items. However, `<md-menu-item>`s have `:hover` styles and `<md-option>`s do not. It's not very user-friendly on a desktop environment.

**Comment by OlsonDev** [comment]
`<md-menu-item>`s seem to get their `:hover` style from this injected rule:

```css
a.md-button:not([disabled]):hover, .md-button:not([disabled]):hover {
  background-color: rgba(158,158,158,0.2);
}
```

because [the demo](https://material.angularjs.org/latest/#/demo/material.components.menu) uses `<md-button>` as the transcluded content of `<md-menu-item>`.

**Comment by OlsonDev** [comment]
Not sure if this should be another issue but using the arrow-keys enables `<md-option>` focus styles. Oddly enough, focusing the already selected `<md-option>` is explicitly not styled. 

```css
md-select-menu md-option:focus:not([selected]) {
  background: rgb(238,238,238);
}
```
This rule on its own would make sense if there were a complementary rule like:
```css
md-select-menu md-option:focus[selected] {
  /* some other background color, or other styles */
}
```
but as it stands, it also hinders usability on the desktop. The `:not([selected])` should be removed.
