### ISSUE TITLE
Tabs:  md-center-tabs not working on master

### ISSUE THREAD

**Issue by Alexandre-io** [angular/material#3549]
Here is the codepen:
http://codepen.io/anon/pen/wayrNB

**Comment by Justkant** [comment]
+1

**Comment by zecaptus** [comment]
+1

here a little css fix : 
```CSS
[md-center-tabs] md-pagination-wrapper{
    position: relative;
    width: initial;
    margin: 0 auto;
    text-align: center;
}

[md-center-tabs] md-pagination-wrapper .md-tab{
    float: none;
    display: inline-block;
}
```
