### ISSUE TITLE
md-select does not show correct border-bottom-color

### ISSUE THREAD

**Issue by mobinni** [angular/material#3759]
I updated my angular to 1.4.3. When I reloaded my project the md-select did not display the correct border-bottom-color. I went into the CSS and forced a hover state and found this css was overriding your own  theme provider override

```css
md-select:not([disabled]):focus .md-select-label {
    border-bottom: 2px solid;
    padding-bottom: 0;
}
```
line 5653 in the compiled angular-material.css

If further info is needed please don't hesitate to post it here.
