### ISSUE TITLE
md-icon sizing not working

### ISSUE THREAD

**Issue by langley-agm** [angular/material#3776]
Documentation says in order to size an icon to 48px you have to apply the following class:
md-48
It never says you have to write that class yourself, and the proposed implementation of the class (which is not mentioned in https://material.angularjs.org/ ) doesn't work. Instead of:
.material-icons.md-48 { font-size: 48px; }
you need to add something like:
.material-icons.md-48 { font-size: 48px; height: 48px; width: 48px; }
otherwise it'll overlap other components.

**Comment by ThomasBurleson** [comment]
Please see our online demo [Font Icons With Ligatures](https://material.angularjs.org/HEAD/#/demo/material.components.icon); which uses Material icons and styles. If you open the CSS sheet, you will see:

```css
.material-icons.md-18 {
  font-size: 18px; }
.material-icons.md-24 {
  font-size: 24px; }
.material-icons.md-36 {
  font-size: 36px; }
.material-icons.md-48 {
  font-size: 48px; }
.material-icons.md-dark {
  color: rgba(0, 0, 0, 0.54); }
.material-icons.md-dark.md-inactive {
  color: rgba(0, 0, 0, 0.26); }
.material-icons.md-light {
  color: white; }
.material-icons.md-light.md-inactive {
  color: rgba(255, 255, 255, 0.3); }
```

Also Google's [Material Icons Developer Guide](http://google.github.io/material-design-icons/) details all this.
