### ISSUE TITLE
sticky footer not work well in md-content

### ISSUE THREAD

**Issue by scarletsky** [angular/material#3977]
demo: http://codepen.io/scarletsky/pen/MwZJrP

I implement sticky footer by the following way: (it is from https://css-tricks.com/snippets/css/sticky-footer/)

```html
<md-toolbar></md-toolbar>

<md-content id="main-wrapper">

  <div id="main"></div>

  <div id="footer"></div>

</md-content>

```

```css
md-toolbar {
  background: red;
  height: 40px;
}

#main-wrapper {
    width: 100%;
    min-height: 100%;
    height: 100%;
    padding: 40px 0 0;
    background-color: green;
}

#main {
    min-height: 100%;
    height: auto;
    margin-bottom: -84px;

    &:after {
        content: "";
        display: block;
        height: 84px;
    }
}

#footer {
    z-index: 9;
    padding: 30px 0;
    background-color: #374147;
    color: #fff;
    font-size: 14px;
    line-height: 30px;
}
```

But the result is that there are two scrollbar in the window(out of `md-content` and in the `md-content`).

How can I fix this? Thanks.

**Comment by norkunas** [comment]
If you don't need to support older browsers then you can use css ```calc``` function with ```vh``` units
or with a little bit changed layout you can make to work in this way http://codepen.io/rscafi/pen/bNXRxY/

**Comment by scarletsky** [comment]
@norkunas 
Thanks for the reply.
In your demo, it seems that the header is no longer always fixed on top ?

**Comment by norkunas** [comment]
http://codepen.io/norkunas/pen/PqXpNR try this. And if you will catch window scrollbar again then  add:
```css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```
http://www.paulirish.com/2012/box-sizing-border-box-ftw/ or import https://github.com/necolas/normalize.css/
