### ISSUE TITLE
::-webkit-input-placeholder is broken

### ISSUE THREAD

**Issue by gligoran** [angular/material#4162]
Mixin ```placeholder-input-color``` in mixins.scss won't work as expected in Chrome.

```scss
@mixin input-placeholder-color($color) {
  &::-webkit-input-placeholder,
  &::-moz-placeholder, /* Firefox 19+ */
  &:-moz-placeholder, /* Firefox 18- */
  &:-ms-input-placeholder {
	color: $color;
  }
}
```

This is because Chrome (at this point in time) fails to parse its part. These have to be separated out like so:

```scss
@mixin input-placeholder-color($color) {
  &::-webkit-input-placeholder { color: $color; }
  &::-moz-placeholder { color: $color; } /* Firefox 19+ */
  &:-moz-placeholder { color: $color; } /* Firefox 18- */
  &:-ms-input-placeholder { color: $color; }
}
```

It would be awesome if this could be fixed, so it works the same across all browsers.

P.S. Found this out the hard way after fiddling with it for more than an hour.

P.S. 2 Also default opacity for the placeholder in Firefox is 0.4. This should be set to some value so it's the same across the board.
