### ISSUE TITLE
md-tab-item shrinks to zero width 

### ISSUE THREAD

**Issue by smashercosmo** [angular/material#4237]
md-tab-item shrinks to zero width when md-tabs are inside md-dialog and md-no-pagination is set.
Here is [demo](http://codepen.io/smashercosmo/pen/xGoxwg). This is also relevant for md-side-nav, see #4065.

**Comment by smashercosmo** [comment]
Workaround for this is to add
```css
.md-tab {
  max-width: 1000px !important;
}
```
