### ISSUE TITLE
$mdDialog initialized with a scope object throws an error when trying to $watch an object

### ISSUE THREAD

**Issue by pencilcheck** [angular/material#4481]
If I initialized $mdDialog with
```
      $mdDialog.show
        clickOutsideToClose: true
        controller: CreateCompanyDialogCtrl
        controllerAs: "ctrl"
        templateUrl: 'app/components/job_internship_postings_dashboard/create_company.tmpl.html'
        parent: angular.element(document.body)
        targetEvent: e
        scope:
          states: $scope.states
```

Then in my `CreateCompanyDialogCtrl` if I do
```
    $scope.$watch "company", (company) ->
      $scope.placeholderJob =
        company: $scope.company
```

The inspector will throw an error about `$scope.$watch` is not a function.

This is on the latest version 0.10.1
