### ISSUE TITLE
md-toast positioned incorrectly when the width of the viewport is exactly 600px

### ISSUE THREAD

**Issue by okelepko** [angular/material#4827]
When the width of the viewport is exactly 600px the following rules clash:

```css
@media (max-width: 600px)
md-toast {
    left: 0;
    right: 0;
    width: 100%;
    max-width: 100%;
    min-width: 0;
    border-radius: 0;
    bottom: 0;
}
```
overriden by:
```css
@media (min-width: 600px)
md-toast.md-left {
    left: 8px;
}
@media (min-width: 600px)
md-toast.md-bottom {
    bottom: 8px;
}
```

![image](https://cloud.githubusercontent.com/assets/9936120/10088520/558454c6-62d0-11e5-960a-ba26ccd3a8be.png)
