### ISSUE TITLE
box-shadow attribute in md-toolbar css

### ISSUE THREAD

**Issue by csotomon** [angular/material#4830]
Version 0.11.0 doesn't have the `box-shadow: 0 2px 5px 0 rgba(0,0,0,.26);` attribute and I can't show the shadows at the tool bar button.

https://ajax.googleapis.com/ajax/libs/angular_material/0.11.0/angular-material.min.css

```css
md-toolbar {
    box-sizing: border-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column;
    position: relative;
    z-index: 2;
    font-size: 20px;
    min-height: 64px;
    width: 100%;
}
```

http://ajax.googleapis.com/ajax/libs/angular_material/0.8.3/angular-material.min.css

```css
md-toolbar {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column;
    position: relative;
    z-index: 2;
    font-size: 1.3em;
    min-height: 64px;
    width: 100%;
    box-shadow: 0 2px 5px 0 rgba(0,0,0,.26);
}
```
