### ISSUE TITLE
md-char-counter breaks visual alignment

### ISSUE THREAD

**Issue by michaelkrog** [angular/material#4872]
After upgrading to 0.11.1, applying the css-class 'md-char-counter' breaks visual alignment.
![skaermbillede 2015-09-28 kl 11 34 02](https://cloud.githubusercontent.com/assets/681472/10132070/e0d78654-65d4-11e5-9d2f-92eb786268f6.png)

[Plunkr](http://plnkr.co/edit/bEaRUfa1dRNpSZL2AX37?p=preview)

**Comment by topherfangio** [comment]
Confirmed. We will get this fixed.

Quick CSS fix/workaround:

```css
.md-char-counter {
  position: absolute !important;
  right: 2px;
}
```
