### ISSUE TITLE
layout-margin / layout-padding and flex="?"

### ISSUE THREAD

**Issue by tinusn** [angular/material#5014]
In release 0.10.x layout-margin and layout-padding works as expected, but in 0.11.2 it does not.

The issue seems to be that the new class based approach does not add "flex" to the class list and is thus not hit by the following:
```css
.layout-margin, .layout-margin > .flex, .layout-margin > .flex-gt-sm, .layout-margin > .flex-md, .layout-margin > .flex-lt-lg {
  margin: 8px; }
```

In 0.10.1:
```html
<div layout="row" layout-margin>
```
becomes
```html
<div layout="row" class="layout layout-row layout-margin">
```
whereas in 0.11.2 it becomes:
```html
<div class="md-layout-row layout-margin">
```

I tried to setup a codepen to demonstrate the issue, but for some reason I cannot get it to work at all with 0.11.2
[0.10.1](http://codepen.io/tinusn/pen/rOyEOK)
[0.11.2](http://codepen.io/tinusn/pen/ZbedQx) (not, this one does not work at all... dunno why)

Please note, that if you just use "flex" instead of "flex="?"" then it works.
