### ISSUE TITLE
md-list-item height break since 0.11.1

### ISSUE THREAD

**Issue by germanferrero** [angular/material#5122]
![breakinchange](https://cloud.githubusercontent.com/assets/7140856/10438314/54e96b54-7109-11e5-9411-3227c21ea9a5.png)

I'd note that md-list-item height is not been calculated to wrap childs. Try to write long text in  < p > element of demo's md-line-3 items. In version 0.11.0 works fine but since 0.11.1  list items overlap.  If desired  behaviour for long text is  hide  overflow with ellipsis, it's also not working. Sory for no codepen.

**Comment by ThomasBurleson** [comment]
Fixed. See https://material.angularjs.org/0.11.3/demo/list

**Comment by germanferrero** [comment]
@ThomasBurleson, i can't see fix. Just same behaviour as yesterday. Workaround for me was setting height:auto to md-list-item. By default, is set to 88px, independently  of children heights

**Comment by ThomasBurleson** [comment]
Will fix with: 

```scss
md-list-item.md-2-line,
md-list-item.md-2-line > .md-no-style {
  height:auto;
  min-height: $list-item-two-line-height;
  &.md-long-text {
      margin:1.6em;
    }
}

md-list-item.md-3-line,
md-list-item.md-3-line > .md-no-style {
  height:auto;
  min-height: $list-item-three-line-height;
  &.md-long-text {
    margin:1.6em;
  }
}
```
