### ISSUE TITLE
Bootstrap .hide negates material .show-*

### ISSUE THREAD

**Issue by noamshemesh** [angular/material#5317]
Hi,
I bumped angular material version to the latest (1.0.0-rc1) to find out that the layout breaks. Any element that I set with `hide` attribute is now hidden even if it has another `show-*` attribute.
The reason is the [infamous `!important`](https://github.com/twbs/bootstrap/issues/9237) that bootstrap adds to their classes (yes, sorry, can't discard bootstrap yet).

I think that this issue exists since version 0.11.0-rc1, one of the breaking changes was [Layout (flex, layout, etc) use Class selectors instead of Attribute selectors](https://github.com/angular/material/blob/master/CHANGELOG.md#breaking-changes-3)

* [Relevant bootstrap code](https://github.com/twbs/bootstrap/blob/master/less/utilities.less#L27-L32)

Thanks!

**Comment by noamshemesh** [comment]
One possible solution is to prefix the `.hide*` and `.show*` classes with `md-` and let the user choose what set of classes to use.

**Comment by epelc** [comment]
You should be able to just override bootstraps `hide` css. See the first answer [here](http://stackoverflow.com/questions/11178673/how-to-override-important). Adding the override after bootstraps should work.

**Comment by noamshemesh** [comment]
@epelc, the `.hide` class definition is in angular material code, I can add another `.hide` class to override bootstrap's class but then I will have to override the `.show-` classes.
Am I missing something?

**Comment by noamshemesh** [comment]
A workaround while waiting for a better solution:
```css
@media (max-width: $layout-breakpoint-sm - 1) {
  .show, .show-sm {
    &.hide {
      display: block !important;
    }
  }
}
@media (min-width: $layout-breakpoint-sm) and (max-width: $layout-breakpoint-md - 1) {
  .show, .show-md, .show-gt-sm {
    &.hide {
      display: block !important;
    }
  }
}

@media (min-width: $layout-breakpoint-md) and (max-width: $layout-breakpoint-lg - 1) {
  .show, .show-lg, .show-gt-sm, .show-gt-md {
    &.hide {
      display: block !important;
    }
  }
}

@media (min-width: $layout-breakpoint-lg) {
  .show, .show-gt-sm, .show-gt-md, .show-gt-lg {
    &.hide {
      display: block !important;
    }
  }
}
```
