### ISSUE TITLE
Input with label text longer than width of input control

### ISSUE THREAD

**Issue by sbondor** [angular/material#5331]
Have a look at the attached pic. The input field is pushed down. It shouldn't be.

![screenshot from 2015-10-23 11 14 51](https://cloud.githubusercontent.com/assets/7798321/10687667/73d39a64-7977-11e5-96d2-ab277aebad83.png)

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate more

**Comment by sbondor** [comment]
@EladBezalel 
Here it is: http://codepen.io/anon/pen/LpQQWv

**Comment by EladBezalel** [comment]
Hey, a quick workaround would be:
```css
md-input-container label {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```
