### ISSUE TITLE
md-fab-speed-dial: md-fab-actions intercepts pointer events when hidden

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [angular/material#5383]
The height of the `md-fab-actions` container within an `md-fab-speed-dial` is non-zero even when hidden. As a result, it is intercepting pointer events. I'm not sure what the best approach is, but the following CSS fixed things for me:
```CSS
md-fab-speed-dial md-fab-actions[aria-hidden] {
	height: 0;
}
```
