### ISSUE TITLE
icon margin issue in md-menu item with rtl

### ISSUE THREAD

**Issue by roidayan** [angular/material#5409]
with html dir="rtl" the menu icons have wrong margin.

![screenshot_5](https://cloud.githubusercontent.com/assets/660126/10787010/7454f048-7d76-11e5-9bce-dd22b6a62d27.png)

http://codepen.io/anon/pen/Qjrqop

I use this css to solve this:
```css
html[dir=rtl] md-menu-item > .md-button md-icon {
    margin: auto 0 auto 16px;
}
```

![screenshot_6](https://cloud.githubusercontent.com/assets/660126/10787013/76be2a2a-7d76-11e5-91eb-2c8cbc34926e.png)

http://codepen.io/anon/pen/eprGoM
