### ISSUE TITLE
can we make the tabs have an option 'md-align-tabs=left'

### ISSUE THREAD

**Issue by loganfreeman** [angular/material#5432]
md-align-tabs=left or md-align-tabs=right

right now it has top or bottom.

**Comment by EladBezalel** [comment]
Right now you can set the tab to position in the center with `md-center-tabs`

to achieve right alignment you can use a temporary override 
```css
.md-tab {
  float: right;
}

md-pagination-wrapper {
  left: initial;
  right: 0;
}
```
