### ISSUE TITLE
Alert dialog over a md-autocomplete template overlaps one with the other

### ISSUE THREAD

**Issue by FabVillegas** [angular/material#5447]
Here, I have a normal autocomplete.
I added a method when an item is not found that enables the user to add the query text to a database for future searches.

![image](https://cloud.githubusercontent.com/assets/7811470/10836434/1d1cc3d4-7e73-11e5-80bd-6633ae4d4af9.png)

Afterwards, a dialog confirms that the query text is uploaded, but surprise, the dialogs mess up each other.

![image](https://cloud.githubusercontent.com/assets/7811470/10836443/3b9c4118-7e73-11e5-91f9-59efb77cc738.png)

I just want to point out this problem.

I think this is just a problem related to the z-index properties.

```css
.md-virtual-repeat-container.md-autocomplete-suggestions-container {
    position: absolute;
    box-shadow: 0 2px 5px rgba(0,0,0,.25);
    height: 225.5px;
    max-height: 225.5px;
    z-index: 80;
}
```
Modifying the value to 80 let the dialog go over the autocomplete template. The original value being z-index: 100.

Also, the md-dialog-container has originally a value of z-index: 80
```css
.md-dialog-container {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-justify-content: center;
    -ms-flex-pack: center;
    justify-content: center;
    -webkit-align-items: center;
    -ms-flex-align: center;
    align-items: center;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 80;
    overflow: hidden;
}
```

Modyfing the value of the md-dialog-container to 101 bugs the autocomplete template

![image](https://cloud.githubusercontent.com/assets/7811470/10836541/4e6a4960-7e74-11e5-8080-e27ccdfdc1a6.png)

I would say to decrease the z-index of the md-autocomplete template instead as a quick fix.
