### ISSUE TITLE
md-fab-speed-dial: does not open/close if $animate.enabled(false) is set

### ISSUE THREAD

**Issue by kschwidder** [angular/material#5600]
if $animate.enable(false) is set then open and close does not work for md-fab-speed-dial since it requires animate in the code. This behaviour does not occur in 0.11.3.

@ThomasBurleson  md-directives: Should the directives still works if $animate is set to false ? If so then all directives should support this. From a framework perspective animation could be disabled which should not affect the md-directives

**Comment by kschwidder** [comment]
The following codepin illustrates the issue 

http://codepen.io/anon/pen/ojazmX

**Comment by topherfangio** [comment]
I agree that directives should work even with `$animate` set to false.

As a temporary workaround, you should be able to add a custom class/CSS which hides/shows the items properly. Something like:

```css
.custom-fab md-fab-actions .md-fab-action-item {
  transition: none;
}
.custom-fab:not(.md-is-open) md-fab-actions {
  visibility: hidden;
}
```

We'll definitely look at providing a more permanent fix though.
