### ISSUE TITLE
Toolbar fade in/out effect

### ISSUE THREAD

**Issue by rudzikdawid** [angular/material#5613]
It would be fantastic if toolbar element could support fade in/out effect like on http://inbox.google.com
![Image of Inbox Fade In/Out Effect](http://dawid.ru/toolbar_fade_in_out.gif)

I made simple example: http://codepen.io/anon/pen/dYgNOe
But i think, that CSS trick with `position: absolute` may cause some problems

```css
.absolute-wrapper {
  position: absolute;
  top: 0;
  display: flex;
  height: 100%;
  width: calc(100% - 32px);
  align-items: center;
  flex-direction: row;
}
```

I had to use a `width: calc()` to subtract padding from `.md-toolbar-tools` element
So I am not fully satisfied with this `.absolute-wrapper` solution
Any ideas, how to improve it?
