### ISSUE TITLE
flex-order doesn't work as expected

### ISSUE THREAD

**Issue by smashercosmo** [angular/material#5646]
flex-order doesn't support negative values, but according to documentation negative values should be supported

**Comment by topherfangio** [comment]
@smashercosmo What version are you using? I remember seeing a recent commit (7264cab4034948f9083ce97e56a45f8f94106067 possibly) that added this support.

**Comment by smashercosmo** [comment]
I just looked at the sources in master and what I see is
```scss
@mixin flex-order-for-name($sizes:null) {
  @if $sizes == null {
    $sizes : '';

    .flex-order {
     order : 0;
    }
  }

  @for $i from 0 through 19 {
    $order : '';
    $suffix : '';

    @each $s in $sizes {
      @if $s != '' { $suffix : '#{$s}-#{$i}'; }
      @else        { $suffix : '#{$i}';       }

      $order : '.flex-order-#{$suffix}';
    }

    #{$order} {
      order: #{$i};
    }
  }
}
```

**Comment by smashercosmo** [comment]
@topherfangio so no negative values as you see)

**Comment by topherfangio** [comment]
It looks like this was added and then removed pretty quickly.

@ThomasBurleson - When you get a chance, you provide some insight?

**Comment by smashercosmo** [comment]
@ThomasBurleson any response on that?

**Comment by ThomasBurleson** [comment]
@smashercosmo - I do not recall why it was redacted. I will restore with:

```scss
@mixin flex-order-for-name($sizes:null) {
  @if $sizes == null {
    $sizes : '';

    .flex-order {
     order : 0;
    }
  }

  @for $i from -10 through 10 {
    $order : '';
    $suffix : '';

    @each $s in $sizes {
      @if $s != '' { $suffix : '#{$s}-#{$i}'; }
      @else        { $suffix : '#{$i}';       }

      $order : '.flex-order-#{$suffix}';
    }

    #{$order} {
      order: #{$i};
    }
  }
}
```
