### ISSUE TITLE
RC4: ng-messages isn't shown when form is submitted, but input is untouched

### ISSUE THREAD

**Issue by chr22** [angular/material#5752]
Try and push the submit button in this [CodePen](http://codepen.io/chr22/pen/QjYdPX) and see that the message is set into DOM but its opacity is 0.

It will need something along the lines of: 
```CSS
form.ng-submitted [ng-messages] {
    opacity: 1;
}
```
