### ISSUE TITLE
rc5 md-dialog fullscreen works only for small screen

### ISSUE THREAD

**Issue by stunaz** [angular/material#5924]
why add the media condition `@media (max-width: $layout-breakpoint-sm)`

```css
@media (max-width: $layout-breakpoint-sm) {
  md-dialog.md-dialog-fullscreen {
    min-height: 100%;
    min-width: 100%;
    border-radius: 0;
  }
}
```

This means we can't force a full screen on a big screen
