### ISSUE TITLE
Breakpoint issue with flex-sm

### ISSUE THREAD

**Issue by julienpa** [angular/material#5995]
I want to apply a 100% flex on a child of a `layout-row` container only for small devices, but it doesn't seem to work since **rc5** and it seems to be because of this code from **angular-material.css** (line 2798):
```css
@media (min-width: 600px) and (max-width: 959px) {
[...]
  .layout-row > .flex-sm-100,
  .layout-sm-row > .flex-sm-100 {
    -webkit-flex: 1 1 100%;
        -ms-flex: 1 1 100%;
            flex: 1 1 100%;
    max-width: 100%;
    max-height: 100%;
    box-sizing: border-box; }
```
This code applies on child elements on a medium screen, and doesn't apply on a small screen
