### ISSUE TITLE
Hide and show attributes not same describe as document

### ISSUE THREAD

**Issue by windhunter89** [angular/material#6113]
Example : 
hide-sm  = display: none on devices less than 600px wide. Which mean screen below 600px the attribute will display none. But from the css line 3071 :
```css
@media (min-width: 600px) and (max-width: 959px) {
  ...
  .hide-sm:not(.show-sm):not(.show) {
    display: none; }
}
```
it show the attribute will hide only when screen is between 600px and 960px, which is suppose for hide-md based on document.

Please correct me if I am wrong.
