### ISSUE TITLE
Is it possible to get theme sass vars ?

### ISSUE THREAD

**Issue by marc-antoinepelletier** [angular/material#6202]
Hey,

I just started to work with material, and I wanted to override the disable button state to keep the color of the theme but just with an opacity at .65. I kind of hurt myself to a wall when I tried to figure how to get the theme color within my sass file.

Mainly, I wanted to do something like that : 

```css
.md-button[disabled] {
  background-color: $primary-color;
  opacity: .65;
  cursor: not-allowed;
}
```

This is a very basic example, but I hope you got my point, I planned to keep using the theme, but just having it fade, or even using another hue would do the job.. But then, the more I dig into, the less I have hope to achieve this.

This might sound silly, but for customisation purpose, this is a big deal for me.

Thanks !
