### ISSUE TITLE
mdIcon vertical margins make it not centered

### ISSUE THREAD

**Issue by angrybacon** [angular/material#6241]
I assume there is a reason behind the irregular margins applied to `<md-icon>`, but what is it?

```scss
md-list-item > div.md-primary > md-icon:not(.md-avatar-icon),
md-list-item > div.md-secondary > md-icon:not(.md-avatar-icon),
md-list-item > md-icon:first-child:not(.md-avatar-icon),
md-list-item > md-icon.md-secondary:not(.md-avatar-icon),
md-list-item .md-list-item-inner > div.md-primary > md-icon:not(.md-avatar-icon),
md-list-item .md-list-item-inner > div.md-secondary > md-icon:not(.md-avatar-icon),
md-list-item .md-list-item-inner > md-icon:first-child:not(.md-avatar-icon),
md-list-item .md-list-item-inner > md-icon.md-secondary:not(.md-avatar-icon) {
  width: 24px;
  margin-top: 16px;
  margin-bottom: 12px;
  box-sizing: content-box;
}
```

It makes the icons unaligned with strings within a `<md-list-item>`:

```html
<md-list>
  <md-list-item ng-click=";">
    <md-icon>home</md-icon>
    <p>Home</p>
  </md-list-item>
</md-list>
```
