### ISSUE TITLE
mdCard: non-matching CSS selector

### ISSUE THREAD

**Issue by Frank3K** [angular/material#6267]
The [compiled material CSS](https://github.com/angular/bower-material/blob/91ada8d78c4b7a37c4f5a294e2c839b00ed329d2/angular-material.css#L9929-L9939) includes an non-matching selector:

``` css
  md-card md-card img,
  md-card > :not(md-card-content) img {
    box-sizing: border-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex: 0 0 auto;
        -ms-flex: 0 0 auto;
            flex: 0 0 auto;
    width: 100%;
    height: auto; }
```

The selector `md-card md-card img` should be `md-card img`. This way the appropriate styles are not applied to images inside cards. As a result of this, issues like #761 are not fixed anymore.

The bug was introduced in 61bb6c47c3242bac7c9993f434a5676f3356d43b:

``` css
  md-card img,
  > :not(md-card-content) img {
    box-sizing: border-box;
    display: flex;
    flex: 0 0 auto;
    width: 100%;
    height: auto;
  }
```

The `md-card` is nested here and should therefore not be here.
