### ISSUE TITLE
datepicker hide icon

### ISSUE THREAD

**Issue by fabiusss** [angular/material#6302]
It would be useful to hide the icon through an attribute, for example: md-hide-icon

**Comment by mattdanna** [comment]
:+1: Agreed, but it doesn't sound like it's a priority at the moment per https://github.com/angular/material/issues/4756#issuecomment-142444212

**Comment by jelbourn** [comment]
If you want to hide the icon, you can use a bit of custom CSS:
```css
.md-datepicker-button {
  display: none;
}
```
