### ISSUE TITLE
docs: virtualRepeat vertical demos have incorrect padding

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#6421]
The vertical demos for virtualRepeat have incorrect padding set on list items that are headers.  See https://material.angularjs.org/HEAD/demo/virtualRepeat scrollTo demo for an example where the header is slightly pushed over.

Browser: Opera 34 (Chrome 47) 
Suggested Fix: Add div:not(.header) rule to the existing padding rule.

```css
.virtualRepeatdemoScrollTo .md-virtual-repeat-container .md-virtual-repeat-offsetter div:not(.header) 
{
  padding-left: 16px; 
}
```
