### ISSUE TITLE
use diaplay:table layout md-tabs

### ISSUE THREAD

**Issue by liujinxing** [angular/material#6437]
Read md-tabs code, found use float:left layout md-tab-item and need calculate all items width when data changed. But i suggest use display:table layout md-pagination-wrapper and md-tab-item. for example:

```css
md-pagination-wrapper {display: table;}
md-tab-item {display: table-cell;}
```

And then no need js code to calculate all items width.

This is just a improve suggest.
