### ISSUE TITLE
Sticky header, with side-nav - scrollable content

### ISSUE THREAD

**Issue by IsNull** [angular/material#6502]
Reading a lot here in the issues about sticky headers using only flex-box, I've managed to achieve a cross browser compatible fixed header solution as suggested in the discussion of #1053 by @epelc. 

Adding a toggle only side-navigation also works without any problems. The Sidenav hovers and thus does not interfere with any layout or scrolling of the page.

Working example with a toggle-able hover side navigation:
```html
<body ng-app="myApp" layout='row'>

    <div layout="column" layout-fill>

        <!-- Sticky header toolbar -->
        <md-toolbar layout="column"> ... </md-toolbar>

        <!-- Side-nav -->
        <md-sidenav class="md-sidenav-left md-whiteframe-z2"
                md-component-id="left"
                md-is-locked-open="false">
        </md-sidenav>

        <md-content flex class='md-padding'>
            <!-- My scrollable content -->
            <div ui-view="content" autoscroll=""></div>
        </md-content>

        <!-- Sticky footer -->
        <footer>My Footer</footer>
    </div>
</body>
```
However, as soon as I try to support a `md-is-locked-open="true"`, everything breaks down - I can not move the side-nav next to the scrollable content without breaking the fixed header toolbar.

My question is, how can i support an locked open side nav `md-is-locked-open="true"`? All my attempts so far cause the sticky header toolbar to break. Is there a clean way how this can be achived with the current angular material?

I am running on the latest version of angular material **1.0.1**.

_____

For reference, I've had a solution which worked exclusively on Safari. The side nav was locked open:
```html
<body ng-app="myApp" layout="column">

        <div layout="column" flex>

            <!-- My sticky toolbar -->
            <md-toolbar layout="column"> ... </md-toolbar>

            <section layout="row" flex>

                <!-- My sidenav, supporting isLockedOpen -->
                <md-sidenav class="md-sidenav-left md-whiteframe-z2"
                        md-component-id="left"
                        md-is-locked-open="true">
                </md-sidenav>

                <!-- My scrollable content -->
                <div class="view-port" layout-margin flex>
                    <div ui-view="content" autoscroll=""></div>
                </div>

            </section>

        </div>
</body>
```

```css
/** main content viewport, almost equal to md-content **/
.view-port {
    display: block;
    position: relative;

    overflow: scroll; /** 'scroll' is required for ios devices **/
    -webkit-overflow-scrolling: touch; /** 'touch' enables ios scroll, requires overflow-scroll **/
}
.view-port[md-scroll-y] {
    overflow-y: auto;
    overflow-x: hidden;
}
.view-port[md-scroll-x] {
    overflow-x: auto;
    overflow-y: hidden;
}
.view-port.autoScroll {
    -webkit-overflow-scrolling: auto;
}
```

I would appreciate any hints how to solve this with clean flexbox declarations.
