### ISSUE TITLE
Override Roboto font with provider

### ISSUE THREAD

**Issue by ByJC** [angular/material#6561]
Hi everyone,

I wanted to know if there is a way to override completely the default font Roboto ? 
I looked for a provider to configure the default font but it seems that the font-familly attribute is hard-coded in the scss.

Could we imagine such a service ? I know that material design specifies only Roboto and Noto but it could be a great feature.
if not do you have a way to do so in my app ? (override css md-* {} etc ... ? )

Bye.

**Comment by chtefi** [comment]
Anybody ?

**Comment by mattdanna** [comment]
Just include a `font-family` override in your application stylesheets, which need to be included in your build *after* your Angular Material dependencies. This is what I use and haven't had any issues:

```css
body {
  font-family: "Comic Sans MS";
}

input,
button,
select,
textarea {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}
```
Demo: http://codepen.io/mattdanna/pen/pgwVzX

And don't worry, I'm not actually using Comic Sans in my app... ;)
