### ISSUE TITLE
Scroll event not firing on md-content

### ISSUE THREAD

**Issue by mackelito** [angular/material#6657]
I need to fire a function on a scroll event... but the directive placed inside a md-content does not fire any scroll events?

```javascript
el.on('scroll', loadData);
```

If I add this to the directive the scroll event works.. but other material directives stops working. (md-toolbar with the md-scroll-shrink attr)
```css
 .productList{
    height: 100vh;
    overflow: scroll;
  }
```

Any ideas?
