### ISSUE TITLE
md-list-item: wrong left and right margins when using md-long-text 

### ISSUE THREAD

**Issue by hacknaked** [angular/material#6783]
When using ```md-list-item``` with ```md-long-text```, left and right margins are wrong:

```css
md-list-item.md-3-line.md-long-text {
    margin: 1.6em;
}
```
It should be

```css
md-list-item.md-3-line.md-long-text {
    margin: 1.6em 0;
}
```
given that the left and right margins are already added in ```md-list-item```.
As a result, list items with ```md-long-text``` have double (left/right) padding than recommended by the Material Design spec http://www.google.com/design/spec/components/lists.html#lists-behavior.
