### ISSUE TITLE
SpeedDial: Using ng-cloak along with ng-hide causes issues.

### ISSUE THREAD

**Issue by topherfangio** [angular/material#6789]
@johnsheldon Creating a separate issue for your `ng-cloak`/`ng-hide` issue so we can track it better.

> Also having this issue, ng-cloak fix worked for one of our speed dials. However, we have another speed dial which is hidden initially using ng-hide, then shown, and when used in conjunction with ng-cloak it causes the action items to be always expanded and invisible, but clickable.
![ng-cloak-with-ng-hide-issue](https://cloud.githubusercontent.com/assets/16325319/11849425/6c035d60-a3ed-11e5-8b0c-6b9042163e55.png)

http://codepen.io/johnsheldon/pen/JGGxNv

_Original comment available at https://github.com/angular/material/issues/6111#issuecomment-165197124_

**Comment by topherfangio** [comment]
Should consider watching for `$md-resize` broadcast.

**Comment by ed4becky** [comment]
I have a codepen at http://codepen.io/ed4becky/pen/eJwYvw that illustrates a similiar issue I have using a FAB in a dialog

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by pvillaverde** [comment]
Since it was closed without a solution, for anyone who runs into this problem, here's the workarround I found. 
The inline styles for the md-fab-action-items where not being placed, so this CSS does their work:

```css
md-fab-speed-dial.md-scale .md-fab-action-item {
		opacity         : 0;
		transform       : scale(0);
		transition-delay: 2ms;
		z-index         : 22;
}

md-fab-speed-dial.md-scale.md-is-open .md-fab-action-item {
		opacity         : 1;
		transform       : scale(1);
		transition-delay: 0;
		z-index         : 22;
}
```
