### ISSUE TITLE
md-list-item md-divider[md-inset]

### ISSUE THREAD

**Issue by ram-you** [angular/material#6862]
According to the specifications, 
https://www.google.com/design/spec/components/lists.html#lists-specs

the left distance should be 72px instead of 96px.

```css 
md-list-item md-divider[md-inset] {
    left: 72px;
    width: calc(100% - 72px);
    margin: 0;
}
```

Thank you.
