### ISSUE TITLE
md-dialog sizing feature broken in new releases

### ISSUE THREAD

**Issue by manish2535** [angular/material#6871]
In recent releases `<md-dialog>` is wrapped into another md-dialog-container. Due to this the sizing feature of the dialogs has stopped working.

The sizing will only work if the parent element has a layout="row" attribute added. Since md-dialog-container is added dynamically, we cant add that attribute either. 

Here is the piece of styling that is supposed to take care of it- 

```css
.layout-row > .flex-66, .layout-row > .flex-66, 
.layout-row > .flex-66, .layout-row > .flex-66 {

  -webkit-flex: 1 1 66%;
      -ms-flex: 1 1 66%;
          flex: 1 1 66%;
  max-width: calc(200% / 3);
  max-height: 100%;
  box-sizing: border-box; 

}
```
