### ISSUE TITLE
mdSelect no longer displays an ellipsis when text overflows.

### ISSUE THREAD

**Issue by shyndman** [angular/material#6906]
Latest version (where bug occurs):
http://codepen.io/shyndman/pen/XXqooq

0.11.2 (correct behaviour):
http://codepen.io/shyndman/pen/ZQoVdx

**Comment by shyndman** [comment]
PS. I'm a Googler. :)

**Comment by shyndman** [comment]
Here's the offending style:

```css
.md-select-value *:first-child {
  ...
  /* flex-shrink of 0 prevents the element from assuming the container's width */
  flex: 1 0 auto; 
}
```
