### ISSUE TITLE
md-icon sizes

### ISSUE THREAD

**Issue by NenadP** [angular/material#6953]
As far as I can see Material icons are not part of the Angular Material. 

I am using therefore https://materialdesignicons.com SVG implementation (because I also need community provided icons which are not part of the   default Material icon set).

It seems to me that I am not able to scale these if I wanted 48px x 48px icon, unless I do:

```scss
md-icon {
  width: 48px;
  height: 48px;

  svg {
    width: 48px;
    height: 48px;
  }
}
```

(I've tried tweaks doing $mdIconProvider, but it doesn't seem to work, if I define alternate "big" icon set sizes are not applying)

Any cleaner approach there?

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd

**Comment by NenadP** [comment]
It's as on https://material.angularjs.org/latest/demo/icon -> Svg Icon Sets, it has additional declaration
```css
.icondemoSvgIconSets .s48 {
  width: 48px;
  height: 48px; 
}
```
so extra custom .s48 class, not part of the angular material pre-defined classes
(btw now I see that it might be sufficient to set it just on parent md-icon element)

Just to confirm I am not missing something and that I need some extra css work here.
