### ISSUE TITLE
Nested md-input-container support for text

### ISSUE THREAD

**Issue by jasonmc86** [angular/material#7102]
Firstly are nested md-input-containers supposed to be a supported feature.
- If so then is there any documentation around this?
- If not could I suggest that ability should be supported? 

Secondly i'm facing an issue when i do nest md-input-container's that the style below applies on any nested input-containers input fields rather than on immediate children only:
for example the following style gets applied to the input bound to testInner even though it has a value.

```css
md-input-container:not(.md-input-has-value) input:not(:focus) {
   color: transparent;
}
``` 

```js
scope.testOuter = "";
scope.testInner = "Hi World";
```

```html
<md-input-container>
    <input ng-model="testOuter"></input>
    <md-input-container>
        <input ng-model="testInner"></input>
    </md-input-container>
</md-input-container>
```
