### ISSUE TITLE
md-button: md-icon-button vertically misaligned, text misaligned when used with icon

### ISSUE THREAD

**Issue by ivoviz** [angular/material#7257]
## Icon Button Alignment

Vertical alignment for the icon within a `md-icon-button` is not correct. 

``` scss

.md-button.md-icon-button {
  width: 39px !important;
  height: 39px !important;
  // Setting line-height to 0px fixes the issue
  line-height: 0px !important;
}
```

_Kudos Workaround_ @bluestella
## Text Alignment

``` html
<md-button>
  <md-icon md-svg-src="your/icon.svg"></md-icon>
  Register Now
</md-button>
```

[Codepen here](http://codepen.io/anon/pen/NxQywr)

Probably a simple `margin-top: -2px` on `md-icon` would solve the problem. (Also tested on the said browsers.)

Using the above snippet the icon is misaligned vertically by 2px.
 Tested in latest Chrome, FF and Edge (31.14267.1000).
ngMaterial Version: 1.0.5
