### ISSUE TITLE
mdButton: IE11 moves content on press

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#7295]
When using an mdButton to create a `<button>` the content inside the first child is moved to the left and down slightly on click.  Pretty sure this is just a default IE thing for buttons.  It is a small thing, but it gives an inconsistent feel across platforms.

Browser: IE11
OS: Windows 7 x64
Suggested fix:
add a rule like the following
```scss
.md-button {
  span:first-child, md-icon:first-child {
    position: relative;
  }
}

```
