### ISSUE TITLE
Pulsating theme colour(s) for md-fab buttons (and buttons in general)

### ISSUE THREAD

**Issue by pmoelgaard** [angular/material#7337]
I want to achieve a pulsating effect on an ```md-fab```-themed button, is this someone has done already ? It seems to must be a requirement someone else has come across... if not, I would love to get cracking making a proposal (or a quick'n'dirty) for it... anyone ?

**Comment by BayanBennett** [comment]
I've used this before, pure CSS:

```css
.pulseGlow {
    -webkit-animation-name: redPulse;
    -webkit-animation-duration: 2.5s;
    -webkit-animation-iteration-count: infinite;
}
@-webkit-keyframes redPulse {
    from { background-color: #fff; -webkit-box-shadow: 0 0 0 #333; }
    50% { background-color: #f00; -webkit-box-shadow: 0 0 16px #f00; }
    to { background-color: #fff; -webkit-box-shadow: 0 0 0 #333; }
```

source: http://zurb.com/playground/radioactive-buttons
