### ISSUE TITLE
Virtual horizontal repeat positionning

### ISSUE THREAD

**Issue by YouriT** [angular/material#7392]
The horizontal usage specifies the height of the container and the height of the cells inside. But in the case of a horizontal one, the absolute positioning doesn't make sense, .md-virtual-repeat-scroller should be a relative position and .md-virtual-repeat-offsetter shall be the same. But it needs to be specific for horizontal repeat otherwise the others will fail.

This would enable dynamic sizes more easily.

**Comment by maximivanov** [comment]
Just hit the same issue today.

**Comment by YouriT** [comment]
@maximivanov yeah was pretty annoying. Juste wrap it and all will be fine.
```scss
.horizontal-hack {
  .md-virtual-repeat-scroller {
    position: inherit;
    .md-virtual-repeat-offsetter {
      position: inherit;
    }
  }
}
```
When using it:
```html
<md-virtual-repeat-container class="horizontal-hack" md-orient-horizontal>
...
</md-virtual-repeat-container>
```

Would be nice to see it integrated :)
