### ISSUE TITLE
Material input container includes slow CSS rules

### ISSUE THREAD

**Issue by bourey** [angular/material#7405]
We have identified several particularly slow CSS rules auto-generated by the Angular Material theme service.  The worst takes over 50ms:

``` css
md-input-container.md-default-theme ng-messages :not(.md-char-counter),
md-input-container ng-messages :not(.md-char-counter),
md-input-container.md-default-theme [ng-messages] :not(.md-char-counter),
md-input-container [ng-messages] :not(.md-char-counter),
md-input-container.md-default-theme ng-message :not(.md-char-counter),
md-input-container ng-message :not(.md-char-counter),
md-input-container.md-default-theme data-ng-message :not(.md-char-counter),
md-input-container data-ng-message :not(.md-char-counter),
md-input-container.md-default-theme x-ng-message :not(.md-char-counter),
md-input-container x-ng-message :not(.md-char-counter),
md-input-container.md-default-theme [ng-message] :not(.md-char-counter),
md-input-container [ng-message] :not(.md-char-counter),
md-input-container.md-default-theme [data-ng-message] :not(.md-char-counter),
md-input-container [data-ng-message] :not(.md-char-counter),
md-input-container.md-default-theme [x-ng-message] :not(.md-char-counter),
md-input-container [x-ng-message] :not(.md-char-counter),
md-input-container.md-default-theme [ng-message-exp] :not(.md-char-counter),
md-input-container [ng-message-exp] :not(.md-char-counter),
md-input-container.md-default-theme [data-ng-message-exp] :not(.md-char-counter),
md-input-container [data-ng-message-exp] :not(.md-char-counter),
md-input-container.md-default-theme [x-ng-message-exp] :not(.md-char-counter),
md-input-container [x-ng-message-exp] :not(.md-char-counter) {
  color: @orangeA700;
}
```
We also observed several slow rules (> 1ms) on radio buttons and md-buttons.
