### ISSUE TITLE
a:not(.md-button) style overriding anchor colors

### ISSUE THREAD

**Issue by amritk** [angular/material#7496]
I just updated to the latest, 1.1.0-RC1 and I got this overriding all of my anchor styles with the accent colour. Is there any way to disable this?

![screen shot 2016-03-09 at 6 22 19 pm](https://cloud.githubusercontent.com/assets/2039539/13657459/3d6a4d28-e624-11e5-98eb-75b9326945de.png)

**Comment by EladBezalel** [comment]
@amritk this is aligned with the spec, you can simply override this with
``` css
a {
  color: initial // or any other color you want
}
```
