### ISSUE TITLE
show-xs would be display elements only on "width< 600px" screens.

### ISSUE THREAD

**Issue by koutat** [angular/material#7627]
when i add "show-xs" attribute, this is displayed in any screen size.

**Comment by himanshuapril1** [comment]
Offcourse it'll, it's clearly mentioned in their docs. Please check the below URL-

[https://material.angularjs.org/latest/layout/options](url)

**Comment by DevVersion** [comment]
`show-xs` is added correctly to the stylesheet.
```css
@media (max-width: 599px) {
  .hide-xs:not(.show-xs):not(.show),.hide:not(.show-xs):not(.show) {
    display:none
  }
```

But it makes not really a sense to use this property, because it only negates `hide-xs`.

For things like this, it would make sense
```html
<div hide-gt-xs show-show-md>
```

(http://codepen.io/DevVersion/pen/mPWPBj)
