### ISSUE TITLE
The styles for `hide/show[-xx[-yy]]` are wrong

### ISSUE THREAD

**Issue by gkalpak** [angular/material#772]
I think that the current implementation of `hide[-xx[-yy]]`/`show[-xx[-yy]]` is kind of broken and confusing (not sure if it is so by design or as a result of a bug in style declarations).

Based on the current styles it seems that `show-xx-yy` can negate `hide-xx-yy`, which seems to have little point (why would I want to define `show-xx-yy` and `hide-xx-yy` on the same element). Furthermore it comes to contradiction with **[the docs](https://material.angularjs.org/#/layout/options)**, which state that `show[-xx[-yy]]` _"negates hide"_ (not `hide[-xx[-yy]]`).

It is makes much more sense (imo) anyway:
Either show the element "by default" and use appropriate `hide-xx[-yy]` attributes to hide it on specific devices or hide the element "by default" (using `hide`) and use appropriate `show-xx[-yy]` attributes to negate `hide` and make the element visible on specific devices.
Mixing both approaches won't help.

--
That said, I believe that:

1. `show` is unnecessary (since elements are shown (i.e. not hidden)) without needing any attribute (and overriding `hide` across all devices doesn't make sense).

2. `show[-xx[-yy]]` should **only** negate `hide` (on appropriate screen-sizes).

According to the above, here are the selectors that should have a `display: none;` style per screen-size:

**any:**      0 < size

  * [hide]:not([show])

**sm:**       0 < size <  600

  * [hide-sm]
  * [hide]:not([show]):not([show-sm])

**gt-sm:**  600 < size

  * [hide-gt-sm]
  * [hide]:not([show]):not([show-gt-sm])

**md:**     600 < size <  960

  * [hide-md]
  * [hide]:not([show]):not([show-md]):not([show-gt-sm])

**gt-md:**  960 < size

  * [hide-gt-md]
  * [hide]:not([show]):not([show-gt-md]):not([show-gt-sm])

**lg:**     960 < size < 1200

  * [hide-lg]
  * [hide]:not([show]):not([show-lg]):not([show-gt-md]):not([show-gt-sm])

**gt-lg:** 1200 < size

  * [hide-gt-lg]
  * [hide]:not([show]):not([show-gt-lg]):not([show-gt-md]):not([show-gt-sm])

--
BTW, this is related to the problem described in #764.

---
<sub>I hope all this makes sense, because I used `make sense` too many times...</sub>

**Comment by ajoslin** [comment]
@altufaltu try `hide show-gt-md` or `hide-sm hide-md`.

**Comment by ajoslin** [comment]
@gkalpak so I'm finally getting to this.

The changes you suggested still broke in some cases.

After much thought, I've taken a simpler approach. I couldn't find any problems with it.

Please poke at it and let me know!

```css
/**
 * `hide-gt-sm show-gt-lg` should hide from 0px to 1200px
 * `show-md hide-gt-sm` should show from 0px to 600px and >960px
 * `hide-gt-md show-gt-sm` should show everywhere (show overrides hide)`
 */

[hide]:not([show]) {
  display: none;
}

// SMALL SCREEN
@media (max-width: $layout-breakpoint-sm) {
  [hide-sm], [hide] {
    &:not([show-sm]):not([show]) {
      display: none;
    }
  }
}

// MEDIUM SCREEN
@media (min-width: $layout-breakpoint-sm) and (max-width: $layout-breakpoint-md) {
  [hide], [hide-gt-sm] {
    &:not([show-gt-sm]):not([show-md]):not([show]) {
      display: none;
    }
  }
  [hide-md]:not([show-md]):not([show]) {
    display: none;
  }
}

// LARGE SCREEN
@media (min-width: $layout-breakpoint-md) and (max-width: $layout-breakpoint-lg) {
  [hide], [hide-gt-sm], [hide-gt-md] {
    &:not([show-gt-sm]):not([show-gt-md]):not([show-lg]):not([show]) {
      display: none;
    }
  }
  [hide-lg]:not([show-lg]):not([show]) {
    display: none;
  }
}

// BIGGER THAN LARGE SCREEN
@media (min-width: $layout-breakpoint-lg) {
  [hide-gt-sm], [hide-gt-md], [hide-gt-lg], [hide] {
    &:not([show-gt-sm]):not([show-gt-md]):not([show-gt-lg]):not([show]) {
      display: none;
    }
  }
}

```
