### ISSUE TITLE
toast disabeling <body> scrolling

### ISSUE THREAD

**Issue by ranbuch** [angular/material#7729]
After toast disappears the body still has a "md-toast-animating" class witch looks like this:

```css
.md-toast-animating {
    overflow: hidden!important;
}
```

and scrolling is disabled.

version:
angular-material@^1.0.6

Thank you.
