### ISSUE TITLE
mdCheckbox :last-of-type inconsistency?

### ISSUE THREAD

**Issue by Phr33d0m** [angular/material#7787]
Hello,

Currently md-checkbox has the css property:
```css
md-checkbox:last-of-type {
    margin-left: 0;
    margin-right: 0;
}
```

Which makes designs quite inconsistent:
![mdcheckboxinc](https://cloud.githubusercontent.com/assets/1591486/14110203/cb502d78-f5c5-11e5-9f0b-cfbbfbc38f89.png)

Is there any reason behind this rule?

Regards.
