### ISSUE TITLE
bug(button): all hyperlinks are styled with default accent color

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#7879]
CodePen: http://codepen.io/robertmesserle/pen/ccc326a07f80a92f7ae5f1b0f9761ac9

This is caused by the following CSS generated by themes:

```css
a.md-default-theme:not(.md-button), a:not(.md-button) {
    color: rgb(255,64,129);
}
```

This will select all hyperlinks (including ones not related to ng-material) that don't have the `md-button` class applied.  This should be scoped to ng-material.
