### ISSUE TITLE
layout-padding sets margin?

### ISSUE THREAD

**Issue by t-esch** [angular/material#788]
Why does the attribute layout-padding sets the css margin value instead of the padding value?

Why

``` css
[layout-padding], [layout-padding] > [flex], [layout-margin], [layout-margin] > [flex] {
  margin: 8px; }
```

instead of

``` css
[layout-padding], [layout-padding] > [flex] {
  padding: 8px; }
[layout-margin], [layout-margin] > [flex] {
  margin: 8px; }
```

(in angular-material.css version 0.6.0-rc3)
