### ISSUE TITLE
mdToolbar: Hide button via ng-show/ng-hide takes a while

### ISSUE THREAD

**Issue by TobiasKrahn** [angular/material#7929]
In Angular Material v1.1.0-rc2 hiding buttons inside `.md-toolbar-tools` via ng-show/ng-hide takes a while. Seems to be caused by this css transition:

```css 
.md-toolbar-tools .md-button, .md-toolbar-tools .md-button.md-icon-button md-icon {
    transition: all 0.5s cubic-bezier(0.35, 0, 0.25, 1);
    transition-property: background-color, fill, color;
}
```

Demo: http://codepen.io/anon/pen/YqYNzX
Browsers: Chrome 49, Firefox 45 and Edge
