### ISSUE TITLE
flex box vendor prefix question

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/material#797]
On a few older phones / tablets with starting with android 4.0.x etc. I was seeing that the flex box layout was not working, I was pretty sure that with the exception of wrap that it should. 

I ran angular-material.css through the vendor prefix playground http://simevidas.jsbin.com/gufoko/quiet to add the older vendor flex box prefix's, applied it, and it started working on those devices. 

Is there a reason that you don't want to add the older prefixes into the mix? 

 e.g 

``` css
// Current
[layout] {
  box-sizing: border-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex; 
}
```

``` css
// Additional prefixes 
[layout] {
  box-sizing: border-box;
  display: -webkit-flex;
  display: -ms-flexbox;

  // Older prefix 
  display: -webkit-box;

  display: flex; 
}
```
