### ISSUE TITLE
bug(select): select menu should not be underlined

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#7988]
In RC2, `md-select` menus are now underlined.  This is breaking a number of layouts and does not appear to be according to spec.

**Comment by clshortfuse** [comment]
Well, sometimes it's underlined, sometimes it's not. I haven't figured out exactly when, but I believe it should be optional.

[material design spec example](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3dUVPRTdfUXlZWnM/components_textfields_single1.png)

The top select isn't underlined, but the bottom one is.

I worked around this by making it optional. See http://codepen.io/shortfuse/pen/oxGowZ

    md-select.md-no-border .md-select-value {
      border-bottom-color: transparent !important;
    }

**Comment by Koslun** [comment]
Got a quick-fix until the RC version with a merged PR #8672 gets merged and the next RC version with it, for those of us not working directly with the master branch:

```CSS
md-select ._md-select-value {
  border-bottom-color: transparent !important;
}
```
Obviously not ideal since it removes the option of showing the underline in some cases while it also depends on a private CSS class that could be changed at any point.

**Comment by topherfangio** [comment]
@Koslun Couldn't you add your own class to the select so that you have more control over when it hides the underline?

```css
md-select.my-custom-class ._md-select-value {
  border-bottom-color: transparent !important;
}
```
