### ISSUE TITLE
md-checkbox: breaking change in CSS style

### ISSUE THREAD

**Issue by xapou** [angular/material#8106]
The documentation [gives an example](https://material.angularjs.org/latest/CSS/checkbox) of styling a checkbox: 
```css
md-checkbox.md-checked.green .md-icon {
 background-color: rgba(0, 255, 0, 0.87);
}
```
This doesn't work since the introduction of private CSS classes (1.1.0-rc1?). 
As a quick workaround - and I know this is far from ideal, I override `_md-icon`:

```css
md-checkbox.md-checked.green ._md-icon {
 background-color: rgba(0, 255, 0, 0.87);
}
```
Is this a bug or is there a new preferred way to style a checkbox?
