### ISSUE TITLE
Creating a 'sandwiched fab button'

### ISSUE THREAD

**Issue by ishankhare07** [angular/material#8384]
**Actual behavior**:
-  What is the issue?  
    How / can this be done in angular material?
-  What is the expected behavior?  
    can be seen in this link -> [material design light templates](https://getmdl.io/templates/text-only/index.html)  
   
![screenshot from 2016-05-09 19-34-41](https://cloud.githubusercontent.com/assets/7482025/15115552/2a1078d2-161d-11e6-828a-a43313e652e4.png)

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: The sandwiched fab button on the right with `+` sign, how does one put it between the elements as shown?

**Angular Versions**: *
-  Angular Version: 1.x
-  Angular Material Version: HEAD

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 49
-  OS: Ubuntu 16.04 64-bit
-  Stack Traces:

**Comment by TobiasKrahn** [comment]
I don't think, that there is something like a class for this, but you can position the fab absolute to one of the elements and set top/bottom to something like -34px. The parent element should be `position: relative`. Maybe this small example helps you.

HTML: 
```html
<body>
  <md-toolbar>
    ...
    <md-button class="md-fab"></md-button>
  </md-toolbar>
  <md-content>
    ...
  </md-content>
</body>
```
CSS:
```css
/*The md-toolbar is already positioned relative by angular material*/
/*md-toolbar {
  position: relative;
}*/

md-toolbar .md-fab {
  position: absolute;
  bottom: -34px;
  right: 34px;
}
```
