### ISSUE TITLE
mdSlider tracks width issue with css transform translate and scale 

### ISSUE THREAD

**Issue by amanullahtanweer** [angular/material#8608]
![8dqxhe8](https://cloud.githubusercontent.com/assets/2203636/15706646/19f42ac2-280e-11e6-8df1-b4245ae723ce.png)

Slider tracks canvas width gets disturb when parent div or element has transform translate transition such as in my case i am animating the whole div 

```css

.step-transition.ng-animate[data-direction="prev"] {
  -webkit-transform-origin: bottom left;
      -ms-transform-origin: bottom left;
          transform-origin: bottom left;
}
.step-transition.ng-animate[data-direction="prev"].ng-enter {
  -webkit-transform: translateX(-100%) scale(0.5);
      -ms-transform: translateX(-100%) scale(0.5);
          transform: translateX(-100%) scale(0.5);
}
```
