### ISSUE TITLE
md-card image border radius

### ISSUE THREAD

**Issue by SPRMat** [angular/material#8696]
```css
md-card.md-default-theme .md-card-image, md-card .md-card-image {
    border-radius: 2px 2px 0 0;
}
```
This css is applied to images inside a card, rounding the top corners to match the card border, but it's also applied when the images in not the first element in the card, 

> i.e. the card has a header. It would probably look better without rounded corners in this case.

Proposed modification:

```css
md-card.md-default-theme .md-card-image, md-card .md-card-image:first-child {
    border-radius: 2px 2px 0 0;
}
```
