### ISSUE TITLE
Themes: Average 315 KB for one theme

### ISSUE THREAD

**Issue by DevVersion** [angular/material#8860]
We have noticed, while working on static theming, that the average theming stylesheet for **only** one theme is about `315 KB` big.

The plain theme stylesheet from the `$MD_THEME_CSS` constant is about `50 KB` big.

So there is a huge difference between the _compiled_ and _base_ CSS.

We have to take look at the generated theme stylesheets and probably find some unnecessary selectors etc.

**Comment by ThomasBurleson** [comment]
Is this due to the mediaQuery selectors in Layouts ?

**Comment by DevVersion** [comment]
No, the layouts are not included in those stylesheets, so it probably relates to the `theming` provider.

**Comment by crisbeto** [comment]
Also to mention that there's a lot of nesting in the theming files. Here's an example:

```css
md-radio-group.md-default-theme.md-hue-1:not([disabled]) .md-primary .md-checked ._md-off,
md-radio-group.md-hue-1:not([disabled]) .md-primary .md-checked ._md-off,
md-radio-group.md-default-theme.md-hue-1:not([disabled]) .md-primary.md-checked ._md-off,
md-radio-group.md-hue-1:not([disabled]) .md-primary.md-checked ._md-off,
md-radio-group.md-default-theme.md-hue-1:not([disabled]).md-primary .md-checked ._md-off,
md-radio-group.md-hue-1:not([disabled]).md-primary .md-checked ._md-off,
md-radio-group.md-default-theme.md-hue-1:not([disabled]).md-primary.md-checked ._md-off,
md-radio-group.md-hue-1:not([disabled]).md-primary.md-checked ._md-off,
md-radio-button.md-default-theme.md-hue-1:not([disabled]) .md-primary .md-checked ._md-off,
md-radio-button.md-hue-1:not([disabled]) .md-primary .md-checked ._md-off,
md-radio-button.md-default-theme.md-hue-1:not([disabled]) .md-primary.md-checked ._md-off,
md-radio-button.md-hue-1:not([disabled]) .md-primary.md-checked ._md-off,
md-radio-button.md-default-theme.md-hue-1:not([disabled]).md-primary .md-checked ._md-off,
md-radio-button.md-hue-1:not([disabled]).md-primary .md-checked ._md-off,
md-radio-button.md-default-theme.md-hue-1:not([disabled]).md-primary.md-checked ._md-off,
md-radio-button.md-hue-1:not([disabled]).md-primary.md-checked ._md-off {
    border-color: rgba(100, 181, 246, 0.87);
}
```
