### ISSUE TITLE
docs(nav-bar): First item text is misaligned.

### ISSUE THREAD

**Issue by topherfangio** [angular/material#8869]
**Actual behavior**:
-  `What is the issue? *` The first tab in our NavBar demo has misaligned text.
-  `What is the expected behavior?` All tabs text should be vertically aligned.

**CodePen** or Steps to reproduce the issue: *
-  `CodePen Demo which shows your issue:` https://material.angularjs.org/HEAD/demo/navBar
-  `Details:` Looks like we have some custom CSS in our docs app that is applying odd styling.

``` css
ul li {
    margin-left: 16px;
    padding: 0;
    margin-top: 3px;
    list-style-position: inside;
}

ul li:first-child {
    margin-top: 0;
}
```

<img width="441" alt="screen shot 2016-06-27 at 11 45 20 am" src="https://cloud.githubusercontent.com/assets/54370/16388164/6b032f86-3c5d-11e6-8aeb-59d7beb65398.png">

**Angular Versions**: *
-  `Angular Version:` N/A
-  `Angular Material Version:` >= 1.1.0-RC5

**Additional Information**:
-  `Browser Type: *` All
-  `Browser Version: *` All
-  `OS: *` All
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.
