### ISSUE TITLE
Documentation: input + ngMessages

### ISSUE THREAD

**Issue by oliversalzburg** [angular/material#8880]
When you're using the `ng-messages` directive an input, and you're *not* using the attribute style on a `div`, the outcome is unexpected and not in line with the documentation.

```html
<div class="ng-message">
```
Creates a block level element.
```html
<ng-message>
```
Creates an inline element.

The result is that the animations don't work correctly. IMHO, it would be nice of this was mentioned in the documentation.

The "fix" for this is to make `ng-message` and `ng-messages` directives block level elements, or to use `div`s as seen in the examples.

```scss
ng-messages {
	display : block;
	ng-message {
		display : block;
	}
}
```
