### ISSUE TITLE
Behaviour differences of md-icon-right on md-input-containers from 1.0.6 onwards

### ISSUE THREAD

**Issue by parky128** [angular/material#8927]
Hi,

I am upgrading an application from AM 1.0.5 to 1.0.9.

I am using md-select inputs inside md-input-containers and also have right aligned md-icons next to the md-select for clearing selected values.

So for example:

```html
<md-input-container class="md-icon-right" flex>
	<label>Something</label>
	<md-select ng-model="option2" flex>
			<md-option ng-repeat="option in options">
			</md-option>
		</md-select>
	<md-icon class="material-icons">X</md-icon>
</md-input-container>
```

This works well enough in 1.0.5, but I see that after upgrading to 1.0.9 the icon appears to the left of the md-select instead.

Appearance in 1.0.5 - http://codepen.io/parky128/pen/rLWJNK
Appearance in 1.0.9 - http://codepen.io/parky128/pen/QEvAXL

I have had some helpful feedback from a contributor on SO as to what the differences are  - see this answer [here](http://stackoverflow.com/questions/38145805/unable-to-right-align-md-icon-inside-md-input-container-on-latest-version-of-ang/38146479#38146479)

This actually exists from 1.0.6 onwards, and seems to only affect md-selects inside md-containers

So at present, I can get the desired behaviour with the following overwrites in my css

```css
md-input-container.md-icon-right>md-icon:last-of-type {
  margin: 0;
  right: 2px;
  left: auto;
}
md-input-container.md-icon-right{
  padding-left: 0 !important;
}
md-input-container.md-has-icon > label {
  left: 0 !important;
}
```

Is this by design in the later versions of 1.x of AM or is this a bug?

Thanks
