### ISSUE TITLE
md-select move body to the top and move overflow from body to html

### ISSUE THREAD

**Issue by jcubic** [angular/material#9008]
**Actual Behavior**:
 -  when I click on ng-select there are inline css added:
```css
body {
   position: fixed;
   width: 100%;
   top: -400px;
}
html {
  overflow-y: scroll;
}
```
and md-backdrop element is added as first child of the body
 -  `What is the expected behavior?` there should be no such css modifications and select should be opened

I'm not able to recreate the issue using code pen, why this css is added?

I've fixed the issue by adding this css:
```css
body {
    position: initial !important;
    top: initial !important;
    overflow: initial !important;
}
html {
    overflow: initial !important;
}
```

**Angular Versions**: *
 -  `Angular Version:`  1.5.6
 -  `Angular Material Version:` 1.1.0-rc.5 and 1.0.9

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` 51.0.2704.103
 -  `OS: *` Windows 7
