### ISSUE TITLE
md-sidenav(md-is-locked-open): animation issue

### ISSUE THREAD

**Issue by U-like** [angular/material#9425]
**Actual Behavior**:
 -  `What is the issue? *` Playing with `md-is-locked-open` of sidenav has a weird animation behavior on opening. Closing it works well.
 -  `What is the expected behavior?` Opening shuold be as smooth as closing.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/gmanrique/pen/rLXxkE
 -  `Details:`

1. Click on `CLICK ME` button to toggle md-is-locked-open value and watch how left sidenav hide correctly.
2. Click same button again and watch how the sidenav appears without animation.

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 52.0.2743.116 (64-bit)
 -  `OS: *` Ubuntu 16.04 (64-bit)
 -  `Stack Traces:` N/A

**Comment by moosebot** [comment]
#9512

**Comment by jayagl** [comment]
Seems to be because of `!important` on the width and min-width on the `md-sidenav.md-closed.md-locked-open-add` selector. Preventing the `md-sidenav.md-closed.md-locked-open-add-active` from taking effect fully:

```css
  md-sidenav.md-closed.md-locked-open-add {
    width: 0 !important;
    min-width: 0 !important;
    transform: translate3d(0%, 0, 0); }

  md-sidenav.md-closed.md-locked-open-add-active {
    transition: width 0.3s cubic-bezier(0.55, 0, 0.55, 0.2), min-width 0.3s cubic-bezier(0.55, 0, 0.55, 0.2);
    width: 220px;
    min-width: 220px;
    transform: translate3d(0%, 0, 0); }
```

I've added this workaround for now: 
```css
md-sidenav.md-closed.md-locked-open-add-active {
    width: 220px !important;
    min-width: 220px !important;
}
```
