### ISSUE TITLE
"md-alt-text" does not show in Firefox

### ISSUE THREAD

**Issue by eassa** [angular/material#9771]
``` html
<span class="md-alt-text">.... </span>
```

``` css
.md-button span.md-alt-text{
    -webkit-box-flex:0;
    -webkit-flex-grow:0;
    flex-grow:0;
    -webkit-align-self:flex-end;
    align-self:flex-end;
    margin:0 8px
}
```

does not show in the toolbar in edge
